export default {
    "format_new_ota_firm_version": "New OTA firmware version : %1$s | %2$s",
    "prompt_ota_firmware_update": "OTA firmware update",
    "net_code_400051": "One or more of the locks you selected are already in offline mode. Please try again.",
    "hint_offline_user_exit_no_lock_connect": "You can't exit out of offline mode until the synchronization is complete.",
    "hint_offline_data_not_synced": "Please try again, the offline mode status needs to sync with Tapplock&#096;s server with internet connection.",
    "prompt_add_finger": "Add fingerprint",
    "hint_lock_user_name": "Lock name/Username",
    "format_new_firm_version": "New firmware version: %1$s | %2$s",
    "prompt_morse_set_length": "Now set your Morse code on your Tapplock with a length of 6-12 presses",
    "hint_morse_all_same": "Morse code cannot be all the same. Your password must contain long and short presses.",
    "hint_insert_box": "Please connect a Tapplock box",
    "hint_add_lock_operation": "Push the power button twice, the LED will be blue and blinking",
    "format_low_power": "%s\\'s power is lower than 20%%, please charge your Tapplock",
    "format_new_firm": "Firmware upgrade %s is ready. Please update your Tapplocks.",
    "format_firm_sync": "Has not been update for %s. Please update the firmware as soon as possible.",
    "format_his_auth_auth_ble": "%1$s %2$s authorized %3$s %4$s permanent Bluetooth access to %5$s",
    "format_his_auth_cancel_ble": "%1$s %2$s revoked %3$s %4$s permanent Bluetooth access to %5$s",
    "format_hit_auth_auth_temp": "%1$s %2$s authorized %3$s %4$s temporary Bluetooth access (%5$s) to %6$s",
    "format_hit_auth_revoke_temp": "%1$s %2$s revoked %3$s %4$s temporary Bluetooth access (%5$s) to %6$s",
    "format_hit_auth_revoke_all_temp": "%1$s %2$s revoked %3$s %4$s all temporary Bluetooth access to %5$s",
    "format_his_set_morse": "%1$s deleted Morse code to %2$s",
    "format_his_delete_morse": "%1$s created Morse code to %2$s",
    "prompt_setup_morse_code": "Setup Morse code",
    "prompt_lock_sync_start": "Data synchronizing, please do not turn off Bluetooth.",
    "prompt_success_auth_user": "The changes to fingerprint access will be live once the lock is synced",
    "prompt_add_lock": "Add Tapplock...",
    "prompt_not_show_again": "Do not show again",
    "hint_lock_ble_unauth": "Unauthorized Bluetooth access",
    "hint_lock_ble_auth": "Authorized Bluetooth access",
    "prompt_delete_morse_success": "The changes to Morse code will be live once the lock is synced",
    "hint_lock_finger_wait_add": "Fingerprint access will be live once the lock is synced",
    "hint_lock_finger_wait_delete": "Fingerprint access will be removed once the lock is synced",
    "prompt_report_auth_ble": "Authorized Bluetooth access",
    "prompt_report_revoke_ble": "Revoked Bluetooth access",
    "prompt_report_create_morse": "Created Morse code",
    "prompt_report_delete_morse": "Delete Morse code",
    "format_action_count": "Audit report: %1$d items",
    "hint_temp_access_auth": "Authorized temporary Bluetooth access",
    "hint_add_temporary_success": "Temporary access authorized!",
    "hint_remove_lock_all_temp": "Are you sure you want to remove all temporary access from %1$s?",
    "hint_remove_lock_one_temp": "Are you sure you want to remove temporary access (%1$s) from %2$s?",
    "hint_remove_user_all_temp": "Are you sure you want to remove all of %1$s\\'s temporary access?",
    "hint_remove_user_one_temp": "Are you sure you want to remove %1$s\\'s temporary access to (%2$s)?",
    "title_license_agreement": "Tapplock\\'s License Agreement",
    "prompt_tutorial_sync": "How to sync the changes to register fingerprint in order to open the lock?",
    "prompt_firm_download": "Downloading and installing firmware, please do not exit Bluetooth mode.",
    "prompt_dfu_lock_ble_hint": "Do not exit Bluetooth mode, please wait a moment.",
    "prompt_dfu_success": "Firmware update complete!",
    "prompt_dfu_fail": "Firmware update failed!",
    "prompt_location_permission_info_less": "If the location permission is not on, you will not be able to connect the lock to our app via Bluetooth.",
    "prompt_location_permission_info_more": "Tapplock app needs internet and location permission available to grab the location from the device. For any functions related to Bluetooth, the location permission have to be turned on, because Tapplock app needs internet and location permission available to grab the location from the phone. Otherwise, you cannot add a new lock, connect the lock to our app via Bluetooth, open the lock via Bluetooth, synchronize the lock, or delete the lock.",
    "format_audit_create_user": "%1$s created an account (email: %2$s name: %3$s)",
    "format_audit_update_user_group": "%1$s changed %2$s\\'s group from %3$s to %4$s",
    "format_audit_update_user_permission": "%1$s changed %2$s\\'s permission from %3$s to %4$s",
    "format_audit_update_user_name": "%1$s changed %2$s\\'s name to %3$s",
    "format_audit_delete_user": "%1$s deleted a user (email: %2$s name: %3$s)",
    "format_audit_staff_login": "%1$s logged in",
    "format_audit_add_rel_bluetooth": "%1$s authorized %2$s permanent Bluetooth access to %3$s",
    "format_audit_delete_rel_bluetooth": "%1$s revoked %2$s permanent Bluetooth access from %3$s",
    "format_audit_set_morse_code": "%1$s created Morse code to %2$s",
    "format_audit_add_rel_temp": "%1$s authorized %2$s temporary Bluetooth access to %3$s",
    "format_audit_delete_rel_temp": "%1$s revoked %2$s temporary Bluetooth access to %3$s",
    "format_audit_delete_all_rel_temp": "%1$s revoked %2$s all temporary Bluetooth access to %3$s",
    "format_audit_delete_morse": "%1$s delete Morse code to %2$s",
    "hint_staff_id": "Staff ID",
    "format_staffId": "Staff ID: %1$s",
    "format_edit_stripe_card": "What do you want to do with **** **** **** %1$s?",
    "net_code_400008": "You do not have the permission to log into the enterprise admin system",
    "net_code_400009": "You cannot delete until all the users from the company are removed",
    "net_code_400012": "You cannot delete the group until all the users from the group are removed",
    "net_code_400014": "The MAC already exists",
    "net_code_400015": "This Tapplock box is currently in used by this company, you cannot delete it",
    "net_code_400017": "You do not have the manage Morse code permission",
    "net_code_400021": "Lock name already exists",
    "net_code_400022": "Authorization has been revoked",
    "net_code_400023": "Invitation code has expired",
    "net_code_400026": "Master account cannot be deleted.",
    "net_code_400028": "The user is not authorized or the authorization has been revoked.",
    "net_code_400031": "Your company has been frozen due to unpaid license fee, please pay through the master account to continue to use or contact your account manager.",
    "net_code_400035": "The total number of locks added has reached this account\\'s limit. Please contact your account manager.",
    "net_code_400046": "An error occurred while processing your card. Please try again.",
    "hint_error_time_out": "Timed out",
    "prompt_admin_view": "View all group info",
    "prompt_manager_morse": "Manage Morse code",
    "prompt_user_notification": "Receive Bluetooth/connection notifications",
    "prompt_assigned_users": "Assigned users",
    "prompt_assigned_locks": "Assigned locks",
    "prompt_add_a_new_box": "Add a new box",
    "prompt_choose_a_box": "Choose a box",
    "hint_delete_morse": "This lock has been set with a Morse code, please press delete button to remove the Morse code, and the Morse code will be reset once the lock is synced.",
    "prompt_unregistered": "Unregistered",
    "prompt_connect": "Connect",
    "format_remain_finger": "Remaining fingerprint: %1$d",
    "prompt_update": "Update",
    "prompt_reset": "Reset",
    "prompt_edit_box": "Edit box",
    "hint_box_name_empty": "Please enter the box name",
    "prompt_reset_box": "Reset box",
    "format_delete_box": "Do you want to delete the box &#096;%1$s&#096;?",
    "hint_finger_enroll_exist": "Fingerprint already exists and cannot be entered repeatedly",
    "hint_finger_enroll_timeout": "Fingerprint enrollment has timed out, please try again",
    "hint_finger_enroll_fail": "Failed to enroll fingerprint, please place your finger onto the fingerprint sensor again.",
    "prompt_box_name": "Box name",
    "prompt_action": "Action",
    "format_audit_add_box": "%1$s added Tapplock box %2$s",
    "format_audit_update_box_name": "%1$s edited Tapplock box %2$s name to %3$s",
    "format_audit_delete_box": "%1$s deleted Tapplock box %2$s",
    "format_hand_finger": "%1$s hand %2$s fingerprint",
    "hint_connect_box": "Please connect a Tapplock box",
    "hint_add_box_success": "Box registered successfully",
    "hint_no_permission_to_edit_finger": "You do not have enough permission to see the fingerprint information.",
    "hint_no_permission_to_edit_user_label": "You do not have enough permissions to modify user labels.",
    "prompt_ignore_this_version": "Ignore this version",
    "hint_box_connect_success": "Tapplock box connected successfully.",
    "hint_box_connect_fail": "Connection failed, please try again.",
    "hint_delete_finger": "Are you sure you want to delete this fingerprint?",
    "hint_open_box_power": "Hold power button until you see blue LED blinking to turn on",
    "format_audit_enroll_finger": "%1$s enrolled fingerprint",
    "format_audit_remove_finger": "%1$s deleted fingerprint",
    "prompt_report_send_delete_finger": "Delete fingerprint",
    "prompt_report_send_add_box": "Add box",
    "prompt_report_send_update_box_name": "Update box name",
    "prompt_report_send_delete_box": "Delete box",
    "prompt_report_send_action_unlock_bluetooth": "Unlock bluetooth",
    "prompt_report_send_action_unlock_fingerprint": "Unlock fingerprint",
    "prompt_report_send_action_unlock_morse_code": "Unlock Morse code",
    "prompt_report_send_action_close_lock": "Close lock",
    "prompt_report_send_action_update_location": "Update location",
    "prompt_report_send_action_update_battery": "Update battery",
    "action_add": "Add",
    "action_login": "Login",
    "action_register_code": "Send verification code",
    "action_resend": "Resend",
    "action_save": "Save",
    "action_yes": "Yes",
    "action_no": "No",
    "action_home": "Home",
    "action_user": "User",
    "action_lock": "Lock",
    "action_setting": "Setting",
    "action_authorize_access": "Authorize access",
    "action_add_fingerprint": "Add fingerprint",
    "prompt_forgot_password": "Forgot password",
    "prompt_group": "Group",
    "prompt_add_group": "Add group",
    "prompt_edit_group": "Edit group",
    "format_delete_group": "Delete the group named %1$s?",
    "prompt_delete_group": "Delete group",
    "prompt_profile": "Profile",
    "prompt_name": "Name",
    "prompt_phone_number": "Phone No.",
    "prompt_phone": "Phone",
    "prompt_email": "Email",
    "prompt_fingerprint": "Fingerprint",
    "prompt_manager": "Manager",
    "prompt_personal_info": "Personal info",
    "prompt_contact_info": "Contact info",
    "prompt_first_name": "First name",
    "prompt_last_name": "Last name",
    "prompt_register_time": "Registration time",
    "prompt_last_login_time": "Last login time",
    "prompt_finger": "Fingerprint",
    "prompt_status": "Status",
    "hint_mail": "Mail",
    "hint_password": "Password",
    "format_resend_countdown": "Resend after %1$ds",
    "hint_firstName": "First name",
    "hint_lastName": "Last name",
    "hint_phone": "Phone",
    "hint_group_name": "Group name",
    "hint_name_phone_email": "Username/Phone No./Email",
    "prompt_save_success": "Saved successfully",
    "hint_success_add_group": "Group added",
    "hint_success_delete_group": "Group deleted",
    "label_tapplock": "Tapplock",
    "label_ads": "World’s first smart fingerprint padlock",
    "label_sign_in": "Sign in",
    "prompt_permission": "Permission",
    "prompt_hand": "Hand",
    "prompt_fingerprint_entry": "Fingerprint entry",
    "prompt_enrol_finger": "Put your finger on the fingerprint reader",
    "prompt_fingers_title": "Fingerprint information",
    "prompt_box": "Box",
    "prompt_box_serial_no": "Box serial no.",
    "prompt_lock_type": "Lock type",
    "prompt_last_sync_time": "Last sync time",
    "prompt_firmware_version": "Firmware version",
    "prompt_battery": "Battery",
    "prompt_bluetooth": "Bluetooth",
    "action_done": "Done",
    "action_cancel": "Cancel",
    "prompt_map": "Map",
    "prompt_lock_name": "Lock name",
    "prompt_edit_user": "Edit user",
    "prompt_admin": "Admin",
    "prompt_user": "User",
    "hint_lock_name": "Lock name",
    "hint_user_name": "Username",
    "prompt_wait_delete": "Deleted",
    "prompt_pending": "Pending",
    "prompt_lock_actions": "Lock actions",
    "prompt_add_a_new_tapplock": "Add a new Tapplock",
    "hint_tapplock_name": "Tapplock name",
    "prompt_connected": "Connected",
    "action_firmware_update": "Firmware update",
    "prompt_firmware_update": "Firmware update",
    "action_mose_code": "Morse code",
    "action_all": "All",
    "action_authorized": "Authorized",
    "action_unauthorized": "Unauthorized",
    "prompt_update_content": "Update content",
    "action_update_now": "Update now",
    "prompt_morse_code": "Morse code",
    "prompt_morse_code_setup_info": "Morse code is a backup access mode that allows you to unlock your padlock using long/short presses without your fingerprint or your phone. \\n\\nAfter the setup, you will be able to unlock your padlock using the combination by pressing the Power Button three (3) times to enter Morse code mode.",
    "prompt_morse_code_short_info": "There are 2 types of Morse code inputs: long and short\\n\\nPressing the Power Button for a short time and letting go will enter a short code, and the LED will blink blue.",
    "prompt_morse_code_long_info": "Pressing and holding the Power Button for 2 seconds and letting go will enter a long code and the LED will blink white.",
    "prompt_short_code": "Short code",
    "prompt_long_code": "Long code",
    "action_short": "Short",
    "action_long": "Long",
    "action_delete": "Delete",
    "prompt_delete_lock": "Delete lock",
    "prompt_tel": "Tel",
    "prompt_post_code": "Postal code",
    "prompt_address": "Address",
    "prompt_company_information": "Company information",
    "prompt_personal_information": "Personal information",
    "prompt_group_all": "All group",
    "prompt_picture": "Picture",
    "action_reset": "Reset",
    "action_user_profile": "User profile",
    "action_tutorial": "Tutorial",
    "action_box_management": "Box management",
    "action_update_pass": "Change password",
    "action_about": "About Us",
    "prompt_register_user": "Registered users",
    "prompt_register_lock": "Registered locks",
    "prompt_groups": "Groups",
    "prompt_choose_a_lock": "Choose a Tapplock",
    "action_edit_access": "Edit access",
    "hint_select_hand": "Please select hand",
    "hint_select_finger": "Please select finger",
    "prompt_group_proportion": "Group proportion",
    "prompt_access_proportion": "Access proportion",
    "prompt_group_unlock_activity": "Group unlock activity",
    "prompt_group_information": "Group information",
    "format_total_pie": "Total\\n%1$s",
    "prompt_legend_access_finger": "Fingerprint access",
    "prompt_legend_access_ble": "Bluetooth access",
    "prompt_unlock": "Unlock",
    "prompt_most_active_users": "Most active users",
    "prompt_most_active_locks": "Most active locks",
    "prompt_fingerprint_access": "Fingerprint access",
    "prompt_bluetooth_access": "Bluetooth access",
    "prompt_audit_report": "Audit report",
    "prompt_time": "Time",
    "prompt_lock_activity": "Lock activity",
    "prompt_last_sync_location": "Last sync location",
    "action_menu_edit": "Edit",
    "action_menu_delete": "Delete",
    "prompt_edit_user_info": "Edit User Info",
    "prompt_access": "Access",
    "prompt_authorization": "Authorization",
    "prompt_user_activity": "User activities",
    "format_data_sync": "Has not been uploaded data for %s",
    "format_his_access_open": "%1$s %2$s opened the lock %3$s",
    "format_his_auth_auth_finger": "%1$s %2$s authorized %3$s %4$s permanent fingerprint access to %5$s",
    "format_his_auth_cancel_finger": "%1$s %2$s revoked %3$s %4$s permanent fingerprint access to %5$s",
    "format_his_sync_location": "%1$s %2$s synced %3$s location",
    "format_his_sync_firm": "%1$s %2$s updated %3$s firmware",
    "format_his_sync_battery": "%1$s %2$s synced %3$s battery",
    "prompt_pass_length_short": "Password must be at least 8 characters",
    "prompt_fill_in_pass": "Please enter your password",
    "prompt_fill_in_confirm_pass": "Please confirm your password",
    "prompt_fill_in_first_name": "Please enter your first name",
    "prompt_fill_in_last_name": "Please enter your last name",
    "prompt_fill_in_old_pass": "Please enter the old password",
    "prompt_pass_mismatch_repass": "Passwords do not match",
    "prompt_pass_same_to_old": "The new password should be different from the old password",
    "prompt_verification_code": "Verification code",
    "prompt_new_password": "New password",
    "prompt_update_password_success": "Password changed",
    "prompt_change_password_success": "Password changed",
    "hint_end_time_after_begin_time": "End time should be later than start time",
    "hint_start_time_after_now": "Start time should be later than now",
    "prompt_start_time": "Start time",
    "prompt_end_time": "End time",
    "hint_group_name_empty": "Please enter the group name",
    "action_logout": "Logout",
    "prompt_logout_message": "Are you sure you want to logout?",
    "prompt_to": "To",
    "format_version": "Version: %1$s",
    "prompt_invalid_lock_name": "Invalid lock name",
    "hint_input_lock_name": "Please enter in the padlock name",
    "hint_select_group": "Please select a group",
    "prompt_error_format_email": "Invalid email format",
    "prompt_fill_in_email": "Please complete your email",
    "prompt_fill_in_email_code": "Please enter your verification code",
    "prompt_delete_lock_success": "Tapplock has been deleted. Please reconnect the Tapplock to the app to reset it.",
    "notification_channel_name": "Synchronizing lock data",
    "notification_channel_dfu_name": "Lock upgrade",
    "notification_channel_fire_name": "Message",
    "prompt_edit_lock_name": "Edit lock name",
    "prompt_lock_first_fail": "This lock has already been registered",
    "prompt_select_lock": "Please select a lock",
    "hint_add_finger_success": "Add finger success",
    "prompt_user_change": "Your account permissions or groups have been modified, please login again",
    "prompt_delete_user": "Are you sure you want to delete this user?",
    "prompt_finger_exist_in_box": "Fingerprint already exists, are you sure you want to use it?",
    "prompt_re_enrol": "Retry",
    "prompt_yes_user_it": "Yes, use it",
    "prompt_lock_sync_finish": "Synchronization finished!",
    "prompt_lock_sync_fail": "Synchronization failed, please try again.",
    "prompt_success_change_user": "User information has been updated",
    "hint_success_add_lock": "Tapplock registered successfully",
    "hint_success_update_lock_name": "Tapplock name saved",
    "hint_success_save_morse": "Morse code saved",
    "hint_latest_lock_firm": "This Tapplock has been upgraded to the latest firmware",
    "format_his_close": "%s was locked",
    "format_his_morse_open": "%s was opened with Morse code",
    "hint_lock_finger_no": "No fingerprint",
    "prompt_unauth": "Unauthorized",
    "prompt_auth": "Authorized",
    "prompt_old_pass": "Old password",
    "prompt_new_pass": "New password",
    "prompt_confirm_new_pass": "Confirm new password",
    "prompt_permission_not_enough": "You do not have enough permissions to modify the user\\'s permissions",
    "prompt_permission_edit_success": "Successfully modified permission",
    "prompt_permission_intro_admin": "Administrative level permissions. Able to make changes at an organizational level.",
    "prompt_permission_intro_admin_users": "Able to view and edit all users with manager and user account status.",
    "prompt_permission_intro_admin_locks": "Able to add, edit, or delete all locks.",
    "prompt_permission_intro_admin_access": "Able to add or delete user access to all locks.",
    "prompt_permission_intro_admin_admin": "Only the Master account can grant other users this permission. Able to manage other users with Admin account status, view all group info, and able to view all users and padlocks.",
    "prompt_permission_intro_admin_groups": "Add, edit, and delete groups.",
    "prompt_permission_intro_admin_view": "Able to view all users and locks.",
    "prompt_permission_intro_admin_report": "Able to view all user activity on the system.",
    "prompt_permission_intro_manger": "Management level permissions. Able to make changes within the groups that the user belongs to.",
    "prompt_permission_intro_manger_users": "Able to view and edit users within the assigned group with the user status.",
    "prompt_permission_intro_manger_locks": "Able to add, edit, or delete locks within the assigned group.",
    "prompt_permission_intro_manger_access": "Able to add or delete user access to locks within the assigned group.",
    "prompt_permission_intro_manger_morse": "Able to assign, edit, or delete Morse code to locks within the assigned group.",
    "prompt_permission_intro_manger_manger": "Only the Master account or Admin status accounts can grant other users this permission. Able to manage other users with Admin account status.",
    "prompt_permission_intro_manger_view": "Able to view all users and locks within the assigned group.",
    "prompt_permission_intro_users": "User level permissions. Able to have basic-level permission pertaining to the employee app.",
    "prompt_permission_intro_users_locks": "Able to view all the locks in all the groups the user belongs to.",
    "prompt_permission_intro_users_history": "Able to view access history of the locks assigned to the user.",
    "prompt_permission_intro_users_notification": "Able to receive live-notification on Bluetooth connections and unlocks",
    "prompt_permission_intro_users_firm": "Able to upgrade lock firmware via Bluetooth connection to the lock.",
    "hin_uncheck_manager_permission": "Please remove the user\\'s manager permission first, then select admin permissions.",
    "prompt_registered": "Registered",
    "prompt_not_registered": "Not registered",
    "prompt_last_week": "Last week",
    "prompt_last_moth": "Last month",
    "prompt_lock_status": "Lock status",
    "hint_add_stripe_card_fail": "The card could not be added",
    "prompt_add_card": "Add card",
    "hint_stripe_update_info_fail": "update fail",
    "prompt_not_payed": "Unpaid",
    "prompt_bills": "Invoices",
    "prompt_invoice_number": "Invoice No.",
    "prompt_bill_title": "Billing cycle",
    "prompt_unit_price": "$/lock",
    "prompt_number_of_locks": "Number of locks",
    "prompt_bill_title_tex": "Tax ($)",
    "prompt_bill_title_total": "Total ($)",
    "prompt_bill_title_status": "Status",
    "prompt_paid": "Paid",
    "prompt_not_pay": "Unpaid",
    "format_bill_to": "Invoice to %s",
    "prompt_card": "Card",
    "prompt_pay_now": "Pay now",
    "prompt_bind_card_title": "Add a card",
    "prompt_bind_card_content2": "Please add a card to pay for the license fee.",
    "hint_bind_card_content": "You have not added a card. In order not to affect the use of the service, please add a card as soon as possible",
    "prompt_pay_success": "Your company has been activated.",
    "hint_delete_pay_card_fail": "Failed to delete the card. Please try again.",
    "prompt_delete_pay_card_title": "Delete card",
    "prompt_delete_pay_card_content": "Are you sure you want to delete the card?",
    "prompt_finger_check_fail": "Failed to enroll fingerprint. Please try again.",
    "prompt_language": "Language",
    "action_report": "Report",
    "format_please_set": "Please set %1$s",
    "prompt_all_funds": "All found",
    "action_delete_lock": "Delete lock",
    "prompt_upload_avatar": "Uploaded profile picture",
    "prompt_upload_avatar_fail": "Fail to upload profile picture, please try again",
    "prompt_upload_avatar_success": "Successfully uploaded profile picture",
    "prompt_splash_slogan": "Fast and easy access for what\\'s important",
    "prompt_permission_intro_manger_report": "Able to view and export audit reports.",
    "hin_uncheck_admin_permission": "Please remover the user\\'s manager permission first, then select admin permissions.",
    "prompt_activity_report": "Activity report",
    "format_pay_summary": "Sub-total: $ %1$s    Tax: $ %2$s    Total: $ %3$s",
    "prompt_create_users": "Create users",
    "prompt_next": "Next",
    "prompt_add": "Add",
    "prompt_export": "Export",
    "prompt_report_sign_up": "Signed up",
    "prompt_report_login_pad": "Logged in via enterprise app",
    "prompt_report_login_staff": "Logged in via staff app",
    "prompt_report_change_pass": "Changed password",
    "prompt_report_change_username": "Edited user\\'s name",
    "prompt_report_enroll_finger": "Fingerprint enrollment",
    "prompt_report_invite_user": "Invited user",
    "prompt_report_create_invite_code": "Created invitation code",
    "prompt_report_create_user": "Created user",
    "prompt_report_delete_user": "Deleted user",
    "prompt_report_add_lock": "Added lock",
    "prompt_report_edit_lock_name": "Edited lock name",
    "prompt_report_delete_lock": "Deleted lock",
    "prompt_report_sync_data": "Synced lock",
    "prompt_report_update_firm": "Updated firmware",
    "prompt_report_auth_finger": "Authorized fingerprint access",
    "prompt_report_revoke_finger": "Revoked fingerprint access",
    "prompt_report_create_group": "Created group",
    "prompt_report_delete_group": "Deleted group",
    "prompt_report_edit_group_name": "Edited group name",
    "prompt_report_edit_user_group": "Modified user\\'s group",
    "prompt_report_edit_user_permission": "Modified user\\'s permission",
    "prompt_report_download": "Downloaded audit report",
    "prompt_report_send_feedback": "Sent feedback",
    "prompt_advance_audit_report": "Advanced audit report",
    "format_export_message": "The audit report will be sent to the email address: %1$s Please check your email for the audit report.",
    "prompt_export_excel_file": "Export audit report",
    "prompt_export_success": "Audit report exported successfully",
    "hint_action_search": "Username/Email/Lock name",
    "prompt_color": "Color",
    "prompt_label": "Label",
    "prompt_add_label": "Add label",
    "prompt_label_name": "Label name",
    "prompt_colors": "Colors",
    "prompt_input_tag_name": "Please fill in label name",
    "prompt_delete_tag": "Delete Label",
    "format_delete_tag": "Do you want to delete label \\'%1$s\\'?",
    "prompt_lock_information": "Lock information",
    "prompt_all_labels": "All labels",
    "prompt_disconnect": "Disconnected",
    "prompt_lock_info": "Lock info",
    "prompt_last_update_time": "Last sync time",
    "prompt_added_labels": "Added labels",
    "prompt_unadded_labels": "Unadded labels",
    "prompt_edit_labels": "Edit labels",
    "prompt_edit_label": "Edit label",
    "prompt_temporary_access": "Temporary access",
    "prompt_permanent_access": "Permanent access",
    "prompt_none": "None",
    "hint_finger_sync": "Fingerprint access is already live",
    "hint_lock_finger_not_auth": "Unauthorized fingerprint access",
    "format_select_lock": "Selected %1$d lock(s)",
    "format_select_user": "Selected %1$d user(s)",
    "hint_select_start_time": "Please select start time",
    "hint_select_end_time": "Please select end time",
    "hint_add_temporary_time": "Please add temporary access time",
    "hint_add_temporary_lock": "Please add temporary access lock",
    "hint_add_temporary_user": "Please add temporary access user",
    "hint_remove_permanent_access": "The permanent access will be removed once you authorize temporary access.",
    "hint_remove_temporary_access": "The temporary access will be removed once you authorize permanent access.",
    "prompt_delete_access": "Delete access",
    "prompt_report_authorized_temp_access": "Authorized temporary access",
    "prompt_report_revoked_temp_access": "Revoked temporary access",
    "prompt_report_revoked_all_temp_access": "Revoked all temporary access",
    "prompt_select_time": "Select time",
    "title_create_users": "Create Users",
    "title_authorize_temporary_access": "Authorize Temporary Access",
    "title_personal_information": "Personal Information",
    "title_unPaid_bills": "Unpaid Invoices",
    "prompt_logging_in_info": "By logging in, you agree to Tapplock’s \\<a href=\"tapplock://com.trapplock.enterprise/license.html\">License Agreement</a>.",
    "prompt_unknown_address": "Unknown address",
    "prompt_tutorial_title": "By selecting a tutorial here we will take you to the specific step you are questioning. You will be navigated away from this page.",
    "prompt_tutorial_lock": "How to add a lock?",
    "prompt_tutorial_user": "How to add a user?",
    "prompt_tutorial_finger": "How to add a fingerprint?",
    "prompt_tutorial_access": "How to manage access?",
    "prompt_tutorial_dialog_content": "Please select next to begin your tutorial where we will guide you through a few steps to help you get set up and learn how to use our management platform.",
    "prompt_tutorial_dialog_title": "Welcome to Tapplock!",
    "action_skip_tutorial": "Skip tutorial",
    "prompt_dfu_firm_updating": "Firmware updating…",
    "prompt_dfu_install_fail": "Installation failed, please try again.",
    "prompt_location_permission_title": "Please turn on location permission in the application settings",
    "prompt_learn_more": "Learn more",
    "prompt_go_to_setting": "Go to setting",
    "format_audit_sign_up": "%1$s signed up with the invitation code %2$s",
    "format_audit_enterprise_login": "%1$s logged in the enterprise system",
    "format_audit_change_password": "%1$s changed password",
    "format_audit_add_group": "%1$s created %2$s",
    "format_audit_delete_group": "%1$s deleted %2$s",
    "format_audit_edit_group": "%1$s changed %2$s name to %3$s",
    "format_audit_add_invite_code": "%1$s created invitation code %2$s",
    "format_audit_invite_users_code": "%1$s invited %2$s user(s)",
    "format_audit_add_lock": "%1$s added %2$s",
    "format_audit_update_lock_name": "%1$s edited %2$s name to %3$s",
    "format_audit_delete_lock": "%1$s deleted %2$s",
    "format_audit_add_rel_fingerprint": "%1$s authorized %2$s permanent fingerprint access to %3$s",
    "format_audit_delete_rel_fingerprint": "%1$s revoked %2$s permanent fingerprint access from %3$s",
    "format_audit_sync_lock_data": "%1$s synced %2$s",
    "format_audit_update_firmware": "%1$s updated %2$s firmware",
    "format_audit_send_feedback": "%1$s sent a feedback",
    "format_audit_enrolled_fingerprint": "%1$s enrolled fingerprint",
    "format_audit_download_advance_audit_report": "%1$s downloaded audit report",
    "prompt_user_info": "User info",
    "prompt_confirm_page": "Confirm page",
    "prompt_confirmation": "Confirmation",
    "prompt_user_creation_failed": "User creation failed",
    "prompt_submit": "Submit",
    "prompt_reason": "Reason",
    "format_users": "%1$d User(s)",
    "prompt_create_user_content": "User creation successfully",
    "prompt_complete_your_information": "Complete your information",
    "prompt_set_as_default": "Set this card as default card",
    "prompt_delete_card": "Delete this card",
    "prompt_all_user_info": "All user info",
    "intro_create_user": "This is where you can create user without review.",
    "intro_add_finger": "ADD FINGERPRINT \\n Click here to add user’s fingerprints",
    "intro_user_permanent_access": "This is where you can authorize user permanent access, and the authorized user can access lock at any time.",
    "intro_user_temporary_access": "This is where you can authorize user temporary access, and the authorized users can access lock for a limited time.",
    "intro_user_history": "This is where you can check history based on the user you are viewing",
    "intro_lock_add_lock": "ADD A NEW TAPPLOCK \\n Click here to add a new Tapplock.",
    "intro_lock_permanent_access": "This is where you can authorize user permanent access, and the authorized user can access lock at any time.",
    "intro_lock_temporary_access": "This is where you can authorize user temporary access, and the authorized users can access lock for a limited time.",
    "intro_lock_history": "This is where you can check history based on the Tapplock you are viewing",
    "prompt_left": "Left",
    "prompt_right": "Right",
    "prompt_finger_thumb": "thumb",
    "prompt_finger_index": "index",
    "prompt_finger_middle": "middle",
    "prompt_finger_ring": "ring",
    "prompt_finger_little": "little",
    "net_code_400000": "Data does not exist or has been deleted",
    "net_code_400001": "The email already exists",
    "net_code_400002": "The verification code is incorrect",
    "net_code_400003": "The user has been approved",
    "net_code_400004": "Invalid invitation code",
    "net_code_400005": "The user is not processed or has been set to leave or freeze.",
    "net_code_400006": "Incorrect email or password",
    "net_code_400007": "Your status is abnormal",
    "net_code_400010": "Email not exists",
    "net_code_400011": "The group already exists",
    "net_code_400013": "The data has been changed. Please try again",
    "net_code_400016": "The fingerprint already exists",
    "net_code_400018": "The old password is incorrect",
    "net_code_400019": "Please remove all the locks before you delete the group",
    "net_code_400020": "This Tapplock box is unregistered or registered to another company",
    "net_code_400024": "Please disable the invitation code before deleting the group",
    "net_code_400027": "The last group cannot be deleted.",
    "net_code_400029": "Please remove all the Tapplocks under the group first.",
    "net_code_400030": "Waiting for admin to approve",
    "net_code_400032": "Payment failed. Please pay with a valid card or try again later.",
    "net_code_400033": "Payment message initialization failed",
    "net_code_400034": "The order is in process. Please try again later",
    "net_code_400037": "You are logging in for the first time, please change your password.",
    "net_code_400038": "Label already exists.",
    "net_code_400043": "Incorrect CVC",
    "net_code_400044": "Card declined",
    "net_code_400045": "Expired card",
    "net_code_400047": "No payable bill",
    "net_code_400048": "Your card\\'s expiration year is invalid",
    "net_not_available": "Network is currently unavailable, please try again later.",
    "net_code_unknown": "Server error",
    "hint_error_network_not_available": "Please check your internet connection",
    "prompt_admin_user": "Manage all users",
    "prompt_admin_lock": "Manage all locks",
    "prompt_admin_access": "Manage all access",
    "prompt_admin_manage": "Manage admins",
    "prompt_admin_group": "Manage groups",
    "prompt_admin_report": "View advanced audit report",
    "prompt_manager_user": "Manage users",
    "prompt_manager_lock": "Manage locks",
    "prompt_manager_access": "Manage access",
    "prompt_manager_history": "View audit report",
    "prompt_manager_manage": "Manage operational permission",
    "prompt_manager_group": "View group info",
    "prompt_user_locks": "View all locks in assigned groups",
    "prompt_user_history": "View all access history in assigned groups",
    "prompt_user_firm": "Initiate firmware updates",
    "prompt_tlbox_disconnect": "Tapplock box disconnected",
    "prompt_update_available": "New version of the app detected. Do you want to update?",
    "prompt_update_force": "New version of the app detected. Please update to continue.",
    "prompt_soft_update": "Software update",
    "prompt_retry": "Retry",
    "prompt_server_upgrade": "The server is under maintenance. Please try again later",
    "prompt_pay_confirm_content": "Are you sure you want to pay this invoice?"
}