export default {
    "format_new_ota_firm_version": "Nueva versión de firmware OTA: %1$s | %2$s",
    "prompt_ota_firmware_update": "Actualización de firmware de OTA",
    "net_code_400051": "Uno o más de los bloqueos que seleccionó ya están en modo fuera de línea. Inténtalo de nuevo.",
    "hint_offline_user_exit_no_lock_connect": "No puede salir del modo fuera de línea hasta que se complete la sincronización.",
    "hint_offline_data_not_synced": "Vuelva a intentarlo, el estado del modo fuera de línea debe sincronizarse con el servidor de Tapplock con conexión a Internet.",
    "prompt_add_finger": "Agregar huellas digitals",
    "hint_lock_user_name": "Nombre del candado/Nombre de usuario",
    "format_new_firm_version": "Nueva versión del firmware: %s | %s",
    "prompt_morse_set_length": "Ahora configure su código Morse en su Tapplock con una longitud de 6 a 12 pulsaciones",
    "hint_morse_all_same": "El código Morse no puede ser todos iguales. Su contraseña debe contener pulsaciones largas y cortas",
    "hint_insert_box": "Por favor conecte la Tapplock box",
    "hint_add_lock_operation": "Presione el botón de encendido dos veces, vea el LED azul parpadeando",
    "format_low_power": "%s batería es inferior al 20%%. Por favor, cargue su Tapplock",
    "format_new_firm": "el nuevo paquete de actualización %s está listo para actualizarse. Por favor actualice sus candados.",
    "format_firm_sync": "No ha sido actualizado para %s. Por favor, actualice el firmware tan pronto como sea posible para garantizar el uso normal",
    "format_his_auth_auth_ble": "%1$s %2$s autorizó el acceso permanente de Bluetooth de %3$s %4$s a %5$s",
    "format_his_auth_cancel_ble": "%1$s %2$s revocó el acceso permanente de Bluetooth de %3$s %4$s a %5$s",
    "format_hit_auth_auth_temp": "%1$s %2$s autorizó el acceso temporal de huellas dactilares de %3$s %4$s (%5$s) a %6$s",
    "format_hit_auth_revoke_temp": "%1$s %2$s revocó el acceso temporal de huellas dactilares de %3$s %4$s (%5$s) a %6$s",
    "format_hit_auth_revoke_all_temp": "%1$s %2$s revocó el todo acceso temporal a Bluetooth de %3$s %4$s a %5$s",
    "format_his_set_morse": "%1$s eliminar el código Morse a %2$s",
    "format_his_delete_morse": " %1$s creó el codigó Morse a %2$s",
    "prompt_setup_morse_code": "Configuración de código Morse",
    "prompt_lock_sync_start": "Sincronizando información, por favor no apague el Bluetooth.",
    "prompt_success_auth_user": "Los cambios en el acceso a la huella digital estarán disponibles en vivo una vez que estén sincronizados por la aplicación del personal",
    "prompt_add_lock": "Agregar Tapplock...",
    "prompt_not_show_again": "No mostrar de nuevo",
    "hint_lock_ble_unauth": "Acceso no autorizado a huellas dactilares",
    "hint_lock_ble_auth": "Acceso Bluetooth autorizado",
    "prompt_delete_morse_success": "El cambio al código Morse se realizará en vivo una vez sincronizado por la aplicación del personal",
    "hint_lock_finger_wait_add": "El acceso a las huellas dactilares será en vivo una vez sincronizado por la aplicación del personal.",
    "hint_lock_finger_wait_delete": "El acceso a la huella digital se eliminará una vez que se haya sincronizado con una aplicación de usuario",
    "prompt_report_auth_ble": "Acceso autorizado por Bluetooth",
    "prompt_report_revoke_ble": "Acceso revocado por Bluetooth",
    "prompt_report_create_morse": "Código Morse creado",
    "prompt_report_delete_morse": "Eliminar código Morse",
    "format_action_count": "Informe de auditoria: %1$d artículos",
    "hint_temp_access_auth": "Acceso temporal autorizado a Bluetooth",
    "hint_add_temporary_success": "Autorizar el acceso temporal añadir con éxito!",
    "hint_remove_lock_all_temp": "¿Está seguro de que desea eliminar todos los accesos temporales de %1$s?",
    "hint_remove_lock_one_temp": "¿Está seguro de que desea eliminar el acceso temporal (%1$s) de from %2$s?",
    "hint_remove_user_all_temp": "¿Estás seguro de que deseas eliminar todo el acceso temporal de %1$?",
    "hint_remove_user_one_temp": "¿Estás seguro de que quiere eliminar el acceso temporal de %1$s a (%2$s)?",
    "title_license_agreement": "Contrato de licencia de Tapplock",
    "prompt_tutorial_sync": "Cómo sincronizar los cambios para registrar la huella dactilar para abrir el bloqueo?",
    "prompt_firm_download": "Descargando el firmware de instalación de Bluetooth, no salgas de Bluetooth.",
    "prompt_dfu_lock_ble_hint": "No salgas de Bluetooth, espera un minuto.",
    "prompt_dfu_success": "Actualización de firmware completa!",
    "prompt_dfu_fail": "Actualización de firmware fallida!",
    "prompt_location_permission_info_less": "Si el permiso de ubicación no está activado, no podrá conectar el bloqueo a nuestra aplicación a través de Bluetooth.",
    "prompt_location_permission_info_more": "La aplicación Tapplock necesita Internet y permiso de ubicación disponible para tomar la ubicación del dispositivo. Para cualquier función relacionada con Bluetooth, el permiso de ubicación debe estar activado, porque la aplicación Tapplock necesita internet y permiso de ubicación disponible para tomar la ubicación desde el teléfono. De lo contrario, no puede agregar un nuevo bloqueo, conectar el bloqueo a nuestra aplicación a través de Bluetooth, abrir el bloqueo a través de Bluetooth, sincronizar el bloqueo o eliminar el bloqueo.",
    "format_audit_create_user": "%1$s creó una cuenta (correo electrónico: %2$s nombre: %3$s)",
    "format_audit_update_user_group": "%1$s cambió el grupo de %2$s de %3$s a %4$s",
    "format_audit_update_user_permission": "%1$s cambió el permiso de %2$s de %3$s a %4$s",
    "format_audit_update_user_name": "%1$s cambió el nombre de %2$s a %3$s",
    "format_audit_delete_user": "%1$s eliminó un usuario (correo electrónico: nombre %2$s: %3$s)",
    "format_audit_staff_login": "%1$s conectado",
    "format_audit_add_rel_bluetooth": "%1$s autorizado %2$s acceso permanente de Bluetooth a %3$s",
    "format_audit_delete_rel_bluetooth": "%1$s revocado %2$s acceso permanente a Bluetooth desde %3$s",
    "format_audit_set_morse_code": "%1$s creó el código Morse para %2$s ",
    "format_audit_add_rel_temp": "%1$s autorizado %2$s acceso temporal de Bluetooth a %3$s",
    "format_audit_delete_rel_temp": "%1$s revocado %2$s acceso temporal de Bluetooth a %3$s",
    "format_audit_delete_all_rel_temp": "%1$s revocado %2$s acceso temporal a Bluetooth a %3$s",
    "format_audit_delete_morse": "%1$s borra el código Morse a %2$s",
    "hint_staff_id": "Identificación del personal",
    "format_staffId": "ID del personal: %1$s ",
    "format_edit_stripe_card": "¿Qué quieres hacer con **** **** **** %1$s?",
    "net_code_400008": "No tienes permiso para iniciar sesión en el sistema Enterprise",
    "net_code_400009": "No puede eliminar hasta que se eliminen todos los usuarios de la empresa",
    "net_code_400012": "No puede eliminar el grupo hasta que se eliminen todos los usuarios del grupo",
    "net_code_400014": "El MAC ya existe",
    "net_code_400015": "Esta Tapplock Box está en uso de la empresa, no se puede borrarlo",
    "net_code_400017": "No tienes permiso para Administrar el código Morse",
    "net_code_400021": "El nombre del candado ya existe",
    "net_code_400022": "La autorización ha sido revocada",
    "net_code_400023": "El código de invitación ha caducado",
    "net_code_400026": "La cuenta maestra no se puede eliminar",
    "net_code_400028": "El usuario no ha autorizado el candado o la autorización ha sido revocada",
    "net_code_400031": "Su compañía ha sido congelada debido a la cuota de licencia sin pagar. Por favor pague a través de la cuenta Master para continuar usando.",
    "net_code_400035": "El número total de candados agregados ha alcanzado el límite de la cuenta. Por favor contacte a su gerente de cuentas.",
    "net_code_400046": "Se produjo un error al procesar su tarjeta.",
    "hint_error_time_out": "Tiempo muerto",
    "prompt_admin_view": "Ver información de todos los grupos",
    "prompt_manager_morse": "Administrar Morse code",
    "prompt_user_notification": "Recibir Bluetooth/Conectar Notificaciónes",
    "prompt_assigned_users": "Usuarios asignados",
    "prompt_assigned_locks": "Cerraduras asignadas",
    "prompt_add_a_new_box": "Agregar una nueva caja",
    "prompt_choose_a_box": "Elige una caja",
    "hint_delete_morse": "Este bloqueo se ha establecido en el código Morse, presione el botón Eliminar para eliminar el código Morse, y el código Morse se restablecerá una vez que conecte el bloqueo.",
    "prompt_unregistered": "No registrado",
    "prompt_connect": "Conectar",
    "format_remain_finger": "Huella digital restante: %1$d",
    "prompt_update": "Actualizar",
    "prompt_reset": "Reiniciar",
    "prompt_edit_box": "Cuadro de edición",
    "hint_box_name_empty": "Por favor, introduzca el nombre del cuadro",
    "prompt_reset_box": "Cuadro de reinicio",
    "format_delete_box": "¿Desea eliminar el cuadro %1$s?",
    "hint_finger_enroll_exist": "La huella digital ya existe y no se puede ingresar repetidamente",
    "hint_finger_enroll_timeout": "Se agotó el tiempo de espera para la inscripción de huellas dactilares. Vuelva a intentarlo.",
    "hint_finger_enroll_fail": "No se pudo registrar la huella digital, vuelva a colocar el dedo en el sensor de huellas digitales.",
    "prompt_box_name": "Nombre de la caja",
    "prompt_action": "Acción",
    "format_audit_add_box": "%1$s agregó Tapplock box %2$s",
    "format_audit_update_box_name": "%1$s editó Tapplock box %2$s nombre a %3$s",
    "format_audit_delete_box": "%1$s eliminado Tapplock box %2$s",
    "format_hand_finger": "Huella digital %1$s %2$s huella digital",
    "hint_connect_box": "Por favor, conecte la caja de Tapplock box",
    "hint_add_box_success": "Caja registrada con éxito",
    "hint_no_permission_to_edit_finger": "No tiene permiso para ver la información de la huella digital.",
    "hint_no_permission_to_edit_user_label": "No tiene suficientes permisos para modificar las etiquetas del usuario.",
    "prompt_ignore_this_version": "Ignora esta versión",
    "hint_box_connect_success": "Tapplock box se conectó correctamente.",
    "hint_box_connect_fail": "Conexión fallida, por favor intente nuevamente.",
    "hint_delete_finger": "¿Seguro que quieres eliminar esta huella digital?",
    "hint_open_box_power": "Mantenga presionado el botón de encendido hasta que vea que el LED azul parpadea para encender",
    "format_audit_enroll_finger": "Huella digital registrada %1$s ",
    "format_audit_remove_finger": "%1$s huella digital eliminada",
    "prompt_report_send_delete_finger": "Eliminar huella digital",
    "prompt_report_send_add_box": "Agregar caja",
    "prompt_report_send_update_box_name": "Nombre del cuadro de actualización",
    "prompt_report_send_delete_box": "Eliminar cuadro",
    "prompt_report_send_action_unlock_bluetooth": "Desbloquear bluetooth",
    "prompt_report_send_action_unlock_fingerprint": "Desbloquear huella digital",
    "prompt_report_send_action_unlock_morse_code": "Desbloquear código Morse",
    "prompt_report_send_action_close_lock": "Cerrar cerradura",
    "prompt_report_send_action_update_location": "Actualizar ubicación",
    "prompt_report_send_action_update_battery": "Actualizar la batería",
    "action_add": "Añadir",
    "action_login": "Iniciar sesión",
    "action_register_code": "Envíe el código de verificación",
    "action_resend": "Reenviar",
    "action_save": "Guardar",
    "action_yes": "Sí",
    "action_no": "No",
    "action_home": "Casa",
    "action_user": "Usuario",
    "action_lock": "Candado",
    "action_setting": "Configuración",
    "action_authorize_access": "Autorizar el acceso",
    "action_add_fingerprint": "Agregar huella digital",
    "prompt_forgot_password": "Olvidé mi contraseña",
    "prompt_group": "Grupo",
    "prompt_add_group": "Agregar grupo",
    "prompt_edit_group": "Editar grupo",
    "format_delete_group": "¿Eliminar el grupo llamado %1$s?",
    "prompt_delete_group": "Borrar grupo",
    "prompt_profile": "Perfil",
    "prompt_name": "Nombre",
    "prompt_phone_number": "Número de teléfono",
    "prompt_phone": "Teléfono",
    "prompt_email": "Correo electrónico",
    "prompt_fingerprint": "Huella digital",
    "prompt_manager": "Gerente",
    "prompt_personal_info": "Informacion personal",
    "prompt_contact_info": "Información de contacto",
    "prompt_first_name": "Primer nombre",
    "prompt_last_name": "Apellido",
    "prompt_register_time": "Hora de registro",
    "prompt_last_login_time": "Última hora de inicio de sesión",
    "prompt_finger": "Huella digital",
    "prompt_status": "Estatus",
    "hint_mail": "Correo",
    "hint_password": "Contraseña",
    "format_resend_countdown": "Reenviar despues de %1$ds",
    "hint_firstName": "Primer nombre",
    "hint_lastName": "Apellido",
    "hint_phone": "Teléfono",
    "hint_group_name": "Nombre del grupo",
    "hint_name_phone_email": "Nombre de usuario / Número de teléfono / Correo electrónico",
    "prompt_save_success": "Guardado exitosamente",
    "hint_success_add_group": "Grupo agregado",
    "hint_success_delete_group": "Grupo eliminado",
    "label_tapplock": "Tapplock",
    "label_ads": "Primer candado de huella digital inteligente del mundo",
    "label_sign_in": "Ingresar",
    "prompt_permission": "Permiso",
    "prompt_hand": "Mano",
    "prompt_fingerprint_entry": "La entrada de huellas digital",
    "prompt_enrol_finger": "Ponga su dedo en el lector de huellas dactilares",
    "prompt_fingers_title": "Información de huella digital",
    "prompt_box": "Caja",
    "prompt_box_serial_no": "Número de serie de la caja",
    "prompt_lock_type": "Tipe de candado",
    "prompt_last_sync_time": "Última hora de sincronización",
    "prompt_firmware_version": "Versión de firmware",
    "prompt_battery": "Batería",
    "prompt_bluetooth": "Bluetooth",
    "action_done": "Hecho",
    "action_cancel": "Cancelar",
    "prompt_map": "Mapa",
    "prompt_lock_name": "Nombre del candado",
    "prompt_edit_user": "Editar usuario",
    "prompt_admin": "Administrador",
    "prompt_user": "Usuario",
    "hint_lock_name": "Nombre del candado",
    "hint_user_name": "Nombre de usuario",
    "prompt_wait_delete": "Eliminado",
    "prompt_pending": "Pendiente",
    "prompt_lock_actions": "Acciones de candado",
    "prompt_add_a_new_tapplock": "Agregar un nuevo Tapplock",
    "hint_tapplock_name": "Nombre de Tapplock",
    "prompt_connected": "Conectado",
    "action_firmware_update": "Actualización del firmware",
    "prompt_firmware_update": "Actualización del firmware",
    "action_mose_code": "Código Morse",
    "action_all": "Todos",
    "action_authorized": "Autorizado",
    "action_unauthorized": "No autorizado",
    "prompt_update_content": "Actualizar el contenido",
    "action_update_now": "Actualizar Ahora",
    "prompt_morse_code": "Código Morse",
    "prompt_morse_code_setup_info": "El código Morse es un modo de acceso de respaldo que le permite desbloquear su candado con pulsaciones largas / cortas sin su huella digital o su teléfono.\\n\\nDespués de la configuración, podrá desbloquear su candado usando la combinación presionando el botón de Encendido tres (3) veces para ingresar al modo de código Morse.",
    "prompt_morse_code_short_info": "Hay 2 tipos de entradas de código Morse: largas y cortas. Al presionar el botón de encendido por un corto tiempo y soltarlo, se ingresará un código corto, y el LED parpadeará en azul.",
    "prompt_morse_code_long_info": "Al presionar y mantener presionado el botón de encendido durante 2 segundos y soltarlo, se ingresará un código largo y el LED parpadeará en blanco.",
    "prompt_short_code": "Código corto",
    "prompt_long_code": "Código largo",
    "action_short": "Corto",
    "action_long": "Largo",
    "action_delete": "Borrar",
    "prompt_delete_lock": "Borrar candado",
    "prompt_tel": "Fon",
    "prompt_post_code": "Código postal",
    "prompt_address": "Dirección",
    "prompt_company_information": "Información de la empresa",
    "prompt_personal_information": "Información personal",
    "prompt_group_all": "Todo grupos",
    "prompt_picture": "Foto",
    "action_reset": "Reiniciar",
    "action_user_profile": "Perfil del usuario",
    "action_tutorial": "Tutorial",
    "action_box_management": "Administración del caja",
    "action_update_pass": "Cambiar contraseña",
    "action_about": "Sobre nosotros",
    "prompt_register_user": "Usuarios Registrados",
    "prompt_register_lock": "Candados registrados",
    "prompt_groups": "Grupos",
    "prompt_choose_a_lock": "Elige un tapplock",
    "action_edit_access": "Editar acceso",
    "hint_select_hand": "Por favor seleccione la mano",
    "hint_select_finger": "Por favor seleccione el dedo",
    "prompt_group_proportion": "Proporción de los grupos",
    "prompt_access_proportion": "Proporción de accesos",
    "prompt_group_unlock_activity": "Actividad de desbloqueos del grupo",
    "prompt_group_information": "Información del grupo",
    "format_total_pie": "Total\\n%1$s",
    "prompt_legend_access_finger": "Acceso huella digital",
    "prompt_legend_access_ble": "Acceso Bluetooth",
    "prompt_unlock": "Desbloquear",
    "prompt_most_active_users": "Usuarios más activos",
    "prompt_most_active_locks": "Candados mas activos",
    "prompt_fingerprint_access": "Acceso huella digital",
    "prompt_bluetooth_access": "Acceso Bluetooth",
    "prompt_audit_report": "Informe de auditoria",
    "prompt_time": "Tiempo",
    "prompt_lock_activity": "Actividad de candado",
    "prompt_last_sync_location": "Ubicación de última sincronización",
    "action_menu_edit": "Editar",
    "action_menu_delete": "Borrar",
    "prompt_edit_user_info": "Editar información del usuario",
    "prompt_access": "Acceso",
    "prompt_authorization": "Autorización",
    "prompt_user_activity": "actividades de usuario",
    "format_data_sync": "No se ha subido información para %s",
    "format_his_access_open": "%1$s %2$s abrió el candado %3$s",
    "format_his_auth_auth_finger": "%1$s %2$s autorizó el acceso permanente de huellas dactilares de %3$s %4$s a %5$s",
    "format_his_auth_cancel_finger": "%1$s %2$s revocó el acceso permanente de huellas digitales de  %3$s %4$s a %5$s",
    "format_his_sync_location": "%1$s %2$s sincronizado %3$s posición",
    "format_his_sync_firm": "%1$s %2$s updated %3$s firmware",
    "format_his_sync_battery": "%1$s %2$s sincronizado %3$s batería",
    "prompt_pass_length_short": "La contraseña debe tener un mínimo de 8 caracteres",
    "prompt_fill_in_pass": "Por favor ingrese su contraseña",
    "prompt_fill_in_confirm_pass": "Por favor confirme su contraseña",
    "prompt_fill_in_first_name": "Por favor ingrese su primer nombre",
    "prompt_fill_in_last_name": "Por favor ingrese su apellido",
    "prompt_fill_in_old_pass": "Por favor ingrese el contraseña anterior",
    "prompt_pass_mismatch_repass": "Las contraseñas no coinciden",
    "prompt_pass_same_to_old": "La nueva contraseña debe ser diferente de la contraseña anterior",
    "prompt_verification_code": "Código de Verificación",
    "prompt_new_password": "Nueva contraseña",
    "prompt_update_password_success": "Contraseña cambiada",
    "prompt_change_password_success": "Contraseña cambiada",
    "hint_end_time_after_begin_time": "La hora de finalización debe ser posterior a la hora de inicio",
    "hint_start_time_after_now": "La hora de inicio debe ser más tarde que ahora",
    "prompt_start_time": "Hora de inicio",
    "prompt_end_time": "Hora de finalización",
    "hint_group_name_empty": "Por favor ingrese el nombre del grupo",
    "action_logout": "Cerrar sesión",
    "prompt_logout_message": "¿Estás seguro de que quieres cerrar sesión?",
    "prompt_to": "Para",
    "format_version": "Versión: %1$s",
    "prompt_invalid_lock_name": "Nombre de candado no válido",
    "hint_input_lock_name": "Por favor ingrese el nombre del candado",
    "hint_select_group": "Por favor seleccione un grupo",
    "prompt_error_format_email": "Formato de correo electrónico inválido",
    "prompt_fill_in_email": "Por favor complete su correo electrónico",
    "prompt_fill_in_email_code": "Por favor ingrese su código de verificación",
    "prompt_delete_lock_success": "Tapplock ha sido borrado. Por favor, vuelva a conectar el Tapplock a la aplicación para restablecerla.",
    "notification_channel_name": "Sincronizando información de candado",
    "notification_channel_dfu_name": "Mejorar candado",
    "notification_channel_fire_name": "Mensaje",
    "prompt_edit_lock_name": "Editar el nombre del candado",
    "prompt_lock_first_fail": "Este candado ya ha sido registrado",
    "prompt_select_lock": "Por favor seleccione un candado",
    "hint_add_finger_success": "Agregar éxito de huella digital",
    "prompt_user_change": "Sus permisos o grupos de cuentas se han modificado. Por favor vuelva a iniciar sesión",
    "prompt_delete_user": "¿Está seguro que desea borrar a este usuario?",
    "prompt_finger_exist_in_box": "La huella digital ya existe, ¿estás seguro de que quieres usarla?",
    "prompt_re_enrol": "Procesar de nuevo",
    "prompt_yes_user_it": "Si usalo",
    "prompt_lock_sync_finish": "Sincronización finalizada!",
    "prompt_lock_sync_fail": "La sincronización falló, por favor intente nuevamente.",
    "prompt_success_change_user": "La información del usuario ha sido actualizada",
    "hint_success_add_lock": "Tapplock registrado exitosamente",
    "hint_success_update_lock_name": "Nombre del Tapplock guardado",
    "hint_success_save_morse": "Código Morse guardado",
    "hint_latest_lock_firm": "Este Tapplock ha sido actualizado con el más reciente firmware",
    "format_his_close": "%s fue cerrado",
    "format_his_morse_open": "%s fue abierto con codigo Morse",
    "hint_lock_finger_no": "Sin huella digital",
    "prompt_unauth": "No autorizado",
    "prompt_auth": "Autorizado",
    "prompt_old_pass": "Contraseña anterior",
    "prompt_new_pass": "Nueva contraseña",
    "prompt_confirm_new_pass": "Confirmar nueva contraseña",
    "prompt_permission_not_enough": "No tiene suficientes permisos para modificar los permisos del usuario",
    "prompt_permission_edit_success": "Permiso modificado exitosamente",
    "prompt_permission_intro_admin": "Permisos nivel administrativo. Capaz de hacer cambios en un nivel de organización.",
    "prompt_permission_intro_admin_users": "Capaz de ver y editar a todos los usuarios con el estado de administrador y cuenta de usuario",
    "prompt_permission_intro_admin_locks": "Capaz de agregar, editar o eliminar todos los candados",
    "prompt_permission_intro_admin_access": "Capaz de agregar o eliminar el acceso de usuario a todos los candados",
    "prompt_permission_intro_admin_admin": "Solo la cuenta Maestra puede otorgar este permiso a otros usuarios. Capaz de administrar a otros usuarios con el estado de la cuenta de Admin, ver toda la información del grupo y poder ver todos los usuarios y candados.",
    "prompt_permission_intro_admin_groups": "Agregar, editar y eliminar grupos",
    "prompt_permission_intro_admin_view": "Capaz de ver todos los usuarios y candados",
    "prompt_permission_intro_admin_report": "Capaz de ver toda la actividad del usuario en el sistema.",
    "prompt_permission_intro_manger": "Permisos de nivel de gestión. Capaz de hacer cambios dentro de los grupos a los que pertenece el usuario",
    "prompt_permission_intro_manger_users": "Capaz de ver y editar usuarios dentro del grupo asignado con el estado del usuario.",
    "prompt_permission_intro_manger_locks": "Capaz de agregar, editar o eliminar candados dentro del grupo asignado",
    "prompt_permission_intro_manger_access": "Capaz de agregar o eliminar el acceso de los usuarios a los candados dentro del grupo asignado",
    "prompt_permission_intro_manger_morse": "Capaz de asignar, editar o eliminar el código Morse a los candados dentro del grupo asignado",
    "prompt_permission_intro_manger_manger": "Solo la cuenta Maestra o las cuentas de estado de Admin pueden otorgar este permiso a otros usuarios. Capaz de administrar a otros usuarios con estado de cuenta de Admin.",
    "prompt_permission_intro_manger_view": "Capaz de ver todos los usuarios y candados dentro del grupo asignado",
    "prompt_permission_intro_users": "Permisos de nivel de usuario. Capaz de tener permiso de nivel básico relativos a la aplicación de los empleados.",
    "prompt_permission_intro_users_locks": "Capaz de ver todos los candados en todos los grupos a los que pertenece el usuario",
    "prompt_permission_intro_users_history": "Capaz de ver el historial de acceso de los candados asignados al usuario",
    "prompt_permission_intro_users_notification": "Capaz de recibir notificaciones en vivo en conexiones Bluetooth y desbloqueos",
    "prompt_permission_intro_users_firm": "Capaz de actualizar el firmware del candado a través de la conexión Bluetooth al candado",
    "hin_uncheck_manager_permission": "Por favor, retire el permiso el administrador del usuario en primer lugar, a continuación, seleccione los permisos de Admin.",
    "prompt_registered": "Registrado",
    "prompt_not_registered": "No registrado",
    "prompt_last_week": "La semana pasada",
    "prompt_last_moth": "El mes pasado",
    "prompt_lock_status": "Estado del candado",
    "hint_add_stripe_card_fail": "La tarjeta no se pudo agregar",
    "prompt_add_card": "Agregar tarjeta",
    "hint_stripe_update_info_fail": "Actualizacion fallida",
    "prompt_not_payed": "No pagado",
    "prompt_bills": "Facturar",
    "prompt_invoice_number": "Número de factura",
    "prompt_bill_title": "Ciclo de facturación",
    "prompt_unit_price": "$/candado",
    "prompt_number_of_locks": "Número de candados",
    "prompt_bill_title_tex": "Impuesto ($)",
    "prompt_bill_title_total": "Total ($)",
    "prompt_bill_title_status": "Estatus",
    "prompt_paid": "Pagado",
    "prompt_not_pay": "No pagado",
    "format_bill_to": "Factura a %s",
    "prompt_card": "Tarjeta",
    "prompt_pay_now": "Pague ahora",
    "prompt_bind_card_title": "Agregar una tarjeta",
    "prompt_bind_card_content2": "Por favor agregue una tarjeta para pagar el costo de la licencia",
    "hint_bind_card_content": "No has agregado una tarjeta. Para no afectar el uso del servicio, agregue una tarjeta lo antes posible",
    "prompt_pay_success": "Tu empresa ha sido activada.",
    "hint_delete_pay_card_fail": "No se pudo eliminar la tarjeta. Por favor volver a probar",
    "prompt_delete_pay_card_title": "Borrar tarjeta",
    "prompt_delete_pay_card_content": "¿Está seguro que quieres borrar la tarjeta?",
    "prompt_finger_check_fail": "No puede inscribir huella digital. Por favor volver a probar",
    "prompt_language": "Idioma",
    "action_report": "Informe",
    "format_please_set": "Por favor establecer %1$s",
    "prompt_all_funds": "Todo encontrado",
    "action_delete_lock": "Eliminar bloqueo",
    "prompt_upload_avatar": "Imagen de perfil cargada",
    "prompt_upload_avatar_fail": "No se pudo subir la imagen de perfil, por favor intente de nuevo",
    "prompt_upload_avatar_success": "Subida exitosamente la imagen de perfil.",
    "prompt_splash_slogan": "Acceso rápido y fácil para lo que es importante",
    "prompt_permission_intro_manger_report": "Capaz de ver y exportar informes de auditoría.",
    "hin_uncheck_admin_permission": "Por favor, elimine primero el permiso del administrador del usuario, luego seleccione los permisos de administrador.",
    "prompt_activity_report": "Informe de actividad",
    "format_pay_summary": "Total parcial: $ %s    Tax: $ %s    Total: $ %s",
    "prompt_create_users": "Crear usuarios",
    "prompt_next": "Siguiente",
    "prompt_add": "Añadir",
    "prompt_export": "Exportar",
    "prompt_report_sign_up": "Inscrito",
    "prompt_report_login_pad": "Iniciar sesión a través de la aplicación empresarial",
    "prompt_report_login_staff": "Conectado a través de la aplicación personal",
    "prompt_report_change_pass": "Contraseña cambiada",
    "prompt_report_change_username": "Nombre de usuario editado",
    "prompt_report_enroll_finger": "Inscripción de huellas dactilares",
    "prompt_report_invite_user": "Usuario invitado",
    "prompt_report_create_invite_code": "Código de invitación creado",
    "prompt_report_create_user": "Usuario creado",
    "prompt_report_delete_user": "Usuario eliminado",
    "prompt_report_add_lock": "Bloqueo añadido",
    "prompt_report_edit_lock_name": "Nombre de bloqueo editado",
    "prompt_report_delete_lock": "Bloqueo eliminado",
    "prompt_report_sync_data": "Bloqueo sincronizado",
    "prompt_report_update_firm": "Firmware actualizado",
    "prompt_report_auth_finger": "Acceso autorizado a huellas dactilares",
    "prompt_report_revoke_finger": "Acceso revocado a la huella dactilar",
    "prompt_report_create_group": "Grupo creado",
    "prompt_report_delete_group": "Grupo borrado",
    "prompt_report_edit_group_name": "Nombre del grupo editado",
    "prompt_report_edit_user_group": "Grupo de usuarios modificado",
    "prompt_report_edit_user_permission": "Permiso del usuario modificado",
    "prompt_report_download": "Informe de auditoría descargado",
    "prompt_report_send_feedback": "Comentarios enviados",
    "prompt_advance_audit_report": "Informe de auditoría anticipada",
    "format_export_message": "El informe de auditoría se enviará a la dirección de correo electrónico: %1$s Por favor revise su correo electrónico para el informe de auditoría.",
    "prompt_export_excel_file": "Informe de Auditoría de Exportaciones",
    "prompt_export_success": "Informe de auditoría exportado exitosamente.",
    "hint_action_search": "Unombre de usuario / correo electrónico / nombre de bloqueo",
    "prompt_color": "Color",
    "prompt_label": "Etiqueta",
    "prompt_add_label": "Añadir etiqueta",
    "prompt_label_name": "Nombre de etiqueta",
    "prompt_colors": "Colores",
    "prompt_input_tag_name": "Por favor complete el nombre de la etiqueta",
    "prompt_delete_tag": "Eliminar etiqueta",
    "format_delete_tag": "¿Quieres borrar la etiqueta \\'%1$s\\'?",
    "prompt_lock_information": "Información de bloqueo",
    "prompt_all_labels": "Todas las etiquetas",
    "prompt_disconnect": "Desconectado",
    "prompt_lock_info": "Información de bloqueo",
    "prompt_last_update_time": "Última hora de sincronización",
    "prompt_added_labels": "Etiquetas añadidas",
    "prompt_unadded_labels": "Etiquetas sin añadir",
    "prompt_edit_labels": "Editar etiquetas",
    "prompt_edit_label": "Editar etiqueta",
    "prompt_temporary_access": "Acceso temporal",
    "prompt_permanent_access": "Acceso permanente",
    "prompt_none": "Ninguno",
    "hint_finger_sync": "El acceso a las huellas dactilares ya está vivo.",
    "hint_lock_finger_not_auth": "Acceso no autorizado a huellas dactilares",
    "format_select_lock": "Seleccionado %1$d candado(s)",
    "format_select_user": "Seleccionado %1$d usuario(s)",
    "hint_select_start_time": "Por favor, seleccione la hora de inicio",
    "hint_select_end_time": "Por favor, seleccione la hora de finalización",
    "hint_add_temporary_time": "Por favor agregue tiempo de acceso temporal",
    "hint_add_temporary_lock": "Por favor agregue bloqueo de acceso temporal",
    "hint_add_temporary_user": "Por favor agregue usuario de acceso temporal",
    "hint_remove_permanent_access": "El acceso permanente se eliminará una vez que autorice el acceso temporal.",
    "hint_remove_temporary_access": "El acceso temporal se eliminará una vez que autorice el acceso permanente.",
    "prompt_delete_access": "Eliminar acceso",
    "prompt_report_authorized_temp_access": "Acceso temporal autorizado",
    "prompt_report_revoked_temp_access": "Acceso temporal revocado",
    "prompt_report_revoked_all_temp_access": "Revocado todo el acceso temporal",
    "prompt_select_time": "Seleccione tiempo",
    "title_create_users": "Crear Usuarios",
    "title_authorize_temporary_access": "Autorizar el acceso temporal",
    "title_personal_information": "Información Personal",
    "title_unPaid_bills": "Facturas sin pagar",
    "prompt_logging_in_info": "Al iniciar sesión, usted acepta el <a href=\"tapplock://com.trapplock.enterprise/license.html\">Acuerdo de licencia</a> de Tapplock.",
    "prompt_unknown_address": "Dirección desconocida",
    "prompt_tutorial_title": "Al seleccionar un tutorial aquí, lo llevaremos al paso específico que está cuestionando. Serás navegado fuera de esta página.",
    "prompt_tutorial_lock": "¿Cómo agregar un candado?",
    "prompt_tutorial_user": "¿Cómo agregar un usuario?",
    "prompt_tutorial_finger": "¿Cómo agregar una huella digital?",
    "prompt_tutorial_access": "¿Cómo gestionar el acceso?",
    "prompt_tutorial_dialog_content": "Seleccione a continuación para comenzar su tutorial, donde lo guiaremos a través de algunos pasos para ayudarlo a configurar y aprender a usar nuestra plataforma de administración.",
    "prompt_tutorial_dialog_title": "Bienvenido a Tapplock!",
    "action_skip_tutorial": "Saltar tutorial",
    "prompt_dfu_firm_updating": "Actualizando firmware...",
    "prompt_dfu_install_fail": "Instalación fallida, por favor intente nuevamente",
    "prompt_location_permission_title": "Active el permiso de ubicación en la configuración de la aplicación",
    "prompt_learn_more": "Aprende más",
    "prompt_go_to_setting": "Ir a la configuración",
    "format_audit_sign_up": "%1$s se registró con el código de invitación %2$s",
    "format_audit_enterprise_login": "%1$s conectado en el sistema empresarial",
    "format_audit_change_password": "%1$s cambió la contraseña",
    "format_audit_add_group": "%1$s creó %2$s",
    "format_audit_delete_group": "%1$s eliminado %2$s",
    "format_audit_edit_group": "%1$s cambió el nombre de %2$s a %3$s",
    "format_audit_add_invite_code": "%1$s creó el código de invitación %2$s",
    "format_audit_invite_users_code": "%1$s invitado %2$s usuario (s)",
    "format_audit_add_lock": "%1$s agregado %2$s",
    "format_audit_update_lock_name": "%1$s editado %2$s nombre a %3$s",
    "format_audit_delete_lock": "%1$s eliminado %2$s",
    "format_audit_add_rel_fingerprint": "%1$s autorizado %2$s acceso permanente de huellas digitales a %3$s ",
    "format_audit_delete_rel_fingerprint": "%1$s revocado %2$s acceso permanente a huellas digitales de %3$s ",
    "format_audit_sync_lock_data": "%1$s sincronizado %2$s ",
    "format_audit_update_firmware": "%1$s actualizado %2$s firmware",
    "format_audit_send_feedback": "%1$s envió un comentario",
    "format_audit_enrolled_fingerprint": "Huella digital registrada %1$s ",
    "format_audit_download_advance_audit_report": "%1$s descargó el informe de auditoría",
    "prompt_user_info": "Información de usuario",
    "prompt_confirm_page": "Confirmar página",
    "prompt_confirmation": "Confirmación",
    "prompt_user_creation_failed": "Creación de usuario fallida",
    "prompt_submit": "Enviar",
    "prompt_reason": "Razón",
    "format_users": "%1$d Usuario (s)",
    "prompt_create_user_content": "Creación de usuario exitosamente",
    "prompt_complete_your_information": "Completa tu información",
    "prompt_set_as_default": "Establecer esta tarjeta como tarjeta predeterminada",
    "prompt_delete_card": "Eliminar esta tarjeta",
    "prompt_all_user_info": "Toda la información del usuario",
    "intro_create_user": "Aquí es donde puedes crear usuarios sin revisión.",
    "intro_add_finger": "AÑADIR FINGERPRINT \\n Haga clic aquí para agregar las huellas digitales del usuario",
    "intro_user_permanent_access": "Aquí es donde puede autorizar el acceso permanente del usuario, y el usuario autorizado puede acceder al bloqueo en cualquier momento.",
    "intro_user_temporary_access": "Aquí es donde puede autorizar el acceso temporal del usuario y los usuarios autorizados pueden acceder al bloqueo por un tiempo limitado.",
    "intro_user_history": "Aquí es donde puede consultar el historial en función del usuario que está viendo.",
    "intro_lock_add_lock": "AÑADIR UN NUEVO TAPPLOCK \\n Haga clic aquí para agregar un nuevo Tapplock.",
    "intro_lock_permanent_access": "Aquí es donde puede autorizar el acceso permanente del usuario, y el usuario autorizado puede acceder al bloqueo en cualquier momento.",
    "intro_lock_temporary_access": "Aquí es donde puede autorizar el acceso temporal del usuario y los usuarios autorizados pueden acceder al bloqueo por un tiempo limitado.",
    "intro_lock_history": "Aquí es donde puede consultar el historial basado en el Tapplock que está viendo",
    "prompt_left": "Izquierda",
    "prompt_right": "Derecho",
    "prompt_finger_thumb": "Pulgar",
    "prompt_finger_index": "Dédo indice",
    "prompt_finger_middle": "Dedo medio",
    "prompt_finger_ring": "Dedo anular",
    "prompt_finger_little": "Dedo meñique",
    "net_code_400000": "La información no existe o ha sido borrada",
    "net_code_400001": "El correo electrónico ya existe",
    "net_code_400002": "El código de verificación es incorrecto",
    "net_code_400003": "El usuario ha sido aprobado",
    "net_code_400004": "Código de invitación inválido",
    "net_code_400005": "El usuario no está procesado o se ha configurado para dejar o congelar ",
    "net_code_400006": "Correo electrónico o contraseña de acceso incorrectos",
    "net_code_400007": "Tu estatus es anormal",
    "net_code_400010": "Correo electrónico inexistente",
    "net_code_400011": "La grupo ya existe",
    "net_code_400013": "Los datos se han cambiado. Por favor volver a probar",
    "net_code_400016": "La huella digital ya existe",
    "net_code_400018": "La contraseña anterior es incorrecta",
    "net_code_400019": "Por favor elimine todos los candados antes de eliminar el grupo",
    "net_code_400020": "Este Tapplock Box no está registrado o está registrado en otra empresa",
    "net_code_400024": "Por favor desactivar el código de invitación antes de eliminar el grupo",
    "net_code_400027": "El último grupo no se puede eliminar",
    "net_code_400029": "Por favor elimine todos los Tapplocks del grupo primero",
    "net_code_400030": "En espera de admin para aprobar",
    "net_code_400032": "Pago fallido. Por favor pague con una tarjeta valida o volver a probar más tarde",
    "net_code_400033": "Falló la inicialización del mensaje de pago",
    "net_code_400034": "El pedido está en proceso. Por favor volver a probar más tarde",
    "net_code_400037": "Usted está ingresando por primera vez, por favor cambie su contraseña.",
    "net_code_400038": "La etiqueta ya existe.",
    "net_code_400043": "CVC incorrecto",
    "net_code_400044": "Tarjeta rechazada",
    "net_code_400045": "tarjeta expirada",
    "net_code_400047": "No hay factura pagadera",
    "net_code_400048": "El año de vencimiento de su tarjeta no es válido.",
    "net_not_available": "La red no está disponible actualmente, inténtalo de nuevo más tarde.",
    "net_code_unknown": "Error del servidor",
    "hint_error_network_not_available": "Verifique su conexión a internet",
    "prompt_admin_user": "Administrar todo el usuarios",
    "prompt_admin_lock": "Administrar todo el candados",
    "prompt_admin_access": "Administrar todo el acceso",
    "prompt_admin_manage": "Administrar admin",
    "prompt_admin_group": "Administrar grupos",
    "prompt_admin_report": "Ver informe de auditoría avanzada",
    "prompt_manager_user": "Administrar usuarios",
    "prompt_manager_lock": "Administrar candados",
    "prompt_manager_access": "Administrar acceso",
    "prompt_manager_history": "Ver informe de auditoría",
    "prompt_manager_manage": "Administrar permisos operacionales",
    "prompt_manager_group": "Ver información del grupo",
    "prompt_user_locks": "Ver todos los candados en los grupos asignados",
    "prompt_user_history": "Ver todo el historial de acceso en grupos asignados",
    "prompt_user_firm": "Iniciar la actualización del firmware",
    "prompt_tlbox_disconnect": "Tapplock Box Desconectado",
    "prompt_update_available": "Nueva versión de la aplicación detectada. Quieres actualizar?",
    "prompt_update_force": "Nueva versión de la aplicación detectada. Por favor, actualice para continuar",
    "prompt_soft_update": "Actualización de software",
    "prompt_retry": "Procesar de nuevo",
    "prompt_server_upgrade": "El servidor está en mantenimiento. Por favor volver a probar más tarde.",
    "prompt_pay_confirm_content": "¿Está seguro que quieres pagar esta factura?"
}