export default {
    label: {
        user: "사용자",
        ok: "승인",
        groupName: "그룹 이름",
        firstName: "이름",
        lastName: "성",
        registerTime: "등록 시간",
        lastLoginTime: "마지막 로그인 시간",
        phoneNo: "전화 번호.",
        tel: "전화",
        postalCode: "우편 번호",
        address: "주소",
        manager: "매니저",
        authorized: "인정 받은",
        unauthorized: "무단",
        pending: "대기 중",
        deleted: "삭제",
        permission: "허가",
        allLabels: "모든 라벨",
        lastSyncLocation: "마지막 동기화 위치",
        time: "시각",
        corpName: "이름",
        oldPassword: "기존 비밀번호",
        newPassword: "새 비밀번호",
        confirmPassword: "비밀번호 확인",
        subTotal: "소계",
        total: "합계",
        optional: "선택 과목"
    },
    title: {
        auditReport: "감사 보고서",
        lock: "자물쇠",
        advancedAuditReport: "고급 감사 보고서",
        card: "카드",
        userProfile: "유저 프로필",
        unpaidBill: "미지급 청구서",
        forgotPassword: "비밀번호를 잊으 셨나요",
        personalInformation: "개인 정보",
        companyInfomation: "회사 정보",
        addLabel: "라벨 추가",
        editLabel: "라벨 수정",
        morseSetup: "모스 부호 설정",
        editLock: "잠금 수정",
        registerUser: "등록 된 사용자들",
        registerLock: "등록 된 잠금",
        groups: "여러 떼",
        groupProportion: "그룹 비율",
        accessProportion: "액세스 비율",
        groupUnlockActivity: "그룹 잠금 해제 활동",
        editUser: "사용자 편집",
        editPermanentAccess: "영구 액세스 수정",
        authorizeTemporaryAccess: "임시 액세스 권한 부여",
        invoiceTo: "송장",
        userCreateFail: "사용자 생성 실패"
    },
    breadCrumb: {
        invoice: "송장",
        management: "조치",
        auditReprot: "감사 보고서",
        report: "보고서",
        dashboard: "계기반"
    },
    tableColumn: {
        group: "그룹",
        email: "이메일",
        name: "이름",
        phone: "전화 번호.",
        staffId: "직원 ID",
        status: "지위",
        battery: "배터리",
        lastSyncTime: "마지막 동기화 시간",
        firmwareVersion: "펌웨어 버전",
        tax: "세금 ($)",
        fingerprint: "지문",
        billCycle: "결제주기",
        unitPrice: "$ / 잠금",
        lockCount: "잠금 수",
        totalMoney: "합계 ($)",
        invoiceNo: "송장 번호",
        boxName: "상자 이름",
        hand: "손",
        finger: "손가락",
        boxSn: "박스 일련 번호",
        lockStatus: "지위",
        profile: "윤곽",
        action: "동작",
        lockType: "잠금 유형",
        bluetooth: "블루투스",
        tempStatus: "임시 액세스",
        permanentStatus: "영구 액세스",
        noneStatus: "없음",
        tag: "상표",
        picture: "그림",
        reason: "이유"
    },
    placeholder: {
        label: "상표",
        labelName: "라벨 이름",
        lockName: "잠금 이름",
        keyword: "아이디 / 전화 번호 / 이메일",
        inputFirstName: "이름 입력",
        inputLastName: "성 입력",
        inputEmailAddress: "이메일 주소 입력",
        inputVerificationCode: "입력 인증 코드",
        atLeastEight: "8 자 이상",
        startTime: "시작 시간",
        endTime: "종료 시간",
        inputGroupName: "입력 그룹 이름",
        firstOrLastName: "사용자 이름",
        userNameOrMail: "아이디 / 이메일",
        userName: "사용자 이름",
        userOrLock: "잠금 이름 / 사용자 이름",
        condition: "행사",
        userNameEmailLockName: "아이디 / 이메일 / 잠금 이름",
        inputUserName: "이메일 입력",
        inputPassword: "비밀번호 입력",
        inputVerifyCode: "입력 인증 코드",
        inputLabelName: "입력 라벨 이름",
        inputYourPhone: "전화 번호 입력",
        inputYourPassword: "비밀번호를 입력하십시오",
        inputYourPasswordAgain: "비밀번호를 다시 입력하십시오",
        selectTime: "시간을 선택하십시오"
    },
    options: {
        createUser: "생성 된 사용자",
        changePassword: "비밀번호 변경",
        addGroup: "생성 된 그룹",
        editGroup: "편집 된 그룹 이름",
        unpaid: "미지급",
        paid: "유료",
        access: "접속하다",
        signUp: "가입",
        updateUserGroup: "수정 된 사용자 그룹",
        updateUserPermission: "수정 된 사용자 권한",
        updateUserName: "편집 된 사용자 이름",
        deleteUser: "삭제 된 사용자",
        enterpriseLogin: "엔터프라이즈 앱을 통해 로그인",
        staffLogin: "직원 앱을 통해 로그인",
        deleteGroup: "삭제 된 그룹",
        addInviteCode: "초대 코드 생성",
        inviteUsersCode: "초대 된 사용자",
        addLock: "추가 된 잠금",
        updateLockName: "편집 된 잠금 이름",
        deleteLock: "삭제 된 잠금",
        openCloseLock: "동기화 된 잠금",
        addAuthBluetooth: "승인 된 블루투스 액세스",
        deleteAuthBluetooth: "블루투스 액세스 취소",
        deleteAuthFingerprint: "지문 액세스 거부",
        syncLockData: "동기화 된 잠금",
        setMorseCode: "모스 부호 작성",
        updateFirmware: "업데이트 된 펌웨어",
        sendFeedback: "보낸 의견",
        enrolledFingerprint: "지문 등록",
        deleteFingerprint: "지문 삭제",
        downloadAdvanceAuditReport: "다운로드 된 감사 보고서",
        addAuthTemp: "승인 된 임시 액세스",
        deleteAuthTemp: "임시 액세스 취소",
        deleteAuthAllTemp: "모든 임시 액세스를 취소했습니다",
        addBox: "상자 추가",
        deleteBox: "상자 삭제",
        noFingerprint: "등록되지 않은",
        haveFingerprint: "등기",
        unlockBluetooth: "블루투스 잠금 해제",
        unlockFingerprint: "지문 인식 잠금 해제",
        unlockMorseCode: "모스 코드 잠금 해제",
        closeLock: "잠금 장치 닫기",
        updateLocation: "위치 업데이트",
        updateBattery: "배터리 업데이트",
        addAuthFingerprint: "승인 된 지문 액세스",
        updateBoxName: "업데이트 상자 이름",
        ringFinger: "반지",
        littleFinger: "작은",
        leftHand: "왼쪽",
        rightHand: "권리",
        authorization: "권한 부여",
        activities: "사용자 활동",
        thumb: "무지",
        indexFinger: "색인",
        middleFinger: "중간"
    },
    btn: {
        search: "수색",
        logOut: "로그 아웃",
        changeVerifyCode: "하나를 바꾸시겠습니까?",
        save: "구하다",
        confirm: "확인",
        cancel: "취소",
        payNow: "지금 지불하세요",
        setDefaultCard: "기본값으로 설정",
        upload: "업로드",
        reset: "다시 놓기",
        next: "다음 것",
        back: "뒤로",
        submit: "제출",
        add: "더하다",
        bulkImport: "대량 수입",
        edit: "편집하다",
        addTemp: "액세스 권한 부여",
        lastMonth: "지난 달",
        lastWeek: "지난주",
        personalInfo: "개인적인 정보",
        permanentAccess: "영구 액세스",
        temporaryAccess: "임시 액세스",
        lockInfo: "정보 잠금",
        authorize: "승인",
        exportXls: "수출",
        loginAgain: "다시 로그인",
        login: "로그인",
        send: "보내다",
        bulkEdit: "일괄 수정"
    },
    message: {
        loginExpired: "로그인이 만료되었으므로 페이지 유지를 취소하거나 다시 로그인 할 수 있습니다",
        completeYourInformation: "아래 양식을 작성하여 계정 등록을 완료하십시오.",
        unkownError: "오류",
        deleteLockConfirm: "이 잠금을 삭제 하시겠습니까?",
        deleteUserConfirm: "이 사용자를 삭제 하시겠습니까?",
        deleteFingerprintConfirm: "이 지문을 삭제 하시겠습니까?",
        prompt: "신속한",
        confirmButtonText: "승인",
        cancelButtonText: "취소",
        deleteSuccess: "성공 삭제",
        addSuccess: "성공 추가",
        deleteFail: "실패 삭제",
        updateSuccess: "업데이트 성공",
        paySuccess: "지불 성공",
        autoCancelPermanent: "임시 액세스 권한을 부여하면 영구 액세스 권한이 제거됩니다.",
        autoCancelTemp: "영구 액세스 권한이 부여되면 임시 액세스 권한이 제거됩니다.",
        deleteTempAuthTime: "`$ {targetName}`에서 임시 액세스 ($ {time})를 제거 하시겠습니까?",
        deleteTempAuth: "이 임시 액세스를 삭제 하시겠습니까?",
        viewOrEditDeletedLock: "잠금이 삭제 된 후에는 잠금 세부 사항을 편집하거나 볼 수 없습니다. 잠금을 동기화하여 삭제를 완료하십시오.",
        deleteDeletedLock: "잠금이 삭제되었습니다. 잠금을 동기화하여 삭제를 완료하십시오.",
        changePasswordSuccess: "비밀번호 변경 성공",
        deleteGroupConfirm: "이 그룹을 삭제 하시겠습니까?",
        deleteCardConfirm: "$ {last4}로 끝나는 카드를 삭제 하시겠습니까?",
        setDefaultCardConfirm: "이 카드를 기본 결제 카드로 설정 하시겠습니까?",
        loadingText: "로딩",
        corpFreeze: "귀하의 회사가 동결되었습니다. 가능한 빨리 지불하십시오",
        welcomeToTapplock: "Tapplock에 오신 것을 환영합니다.",
        firstSmartPadlock: "세계 최초의 스마트 지문 자물쇠.",
        resetPassword: "아래 양식을 작성하여 비밀번호를 재설정하십시오.",
        createUserRadio: "한 번에 하나씩 사용자 생성",
        createUserRadioMsg: "정보를 입력하여 회사에 새로운 사용자 추가",
        importUserRadio: "대량 수입 사용자",
        importUserRadioMsg: "한 번에 여러 사용자를 만듭니다."
    },
    formValidate: {
        groupNameEmpty: "그룹 이름은 비워 둘 수 없습니다",
        lockNameNotEmpty: "잠금 이름은 비워 둘 수 없습니다",
        emailEmpty: "이메일은 비워 둘 수 없습니다",
        firstNameEmpty: "이름은 비워 둘 수 없습니다",
        groupNotSelected: "그룹을 선택하십시오",
        userNotAdd: "사용자를 추가하십시오",
        wrongEmailFormat: "올바른 사서함 형식을 입력하십시오",
        passwordLength: "비밀번호는 8 자리 이상이어야합니다",
        verifyCodeNotEmpty: "인증 코드는 비워 둘 수 없습니다",
        passwordNotEmpty: "비밀번호는 비워 둘 수 없습니다",
        labelNameEmpty: "라벨 이름은 비워 둘 수 없습니다"
    },
    permission: {
        master: "석사",
        manageAllUsers: "모든 사용자 관리",
        manageAllLocks: "모든 잠금 관리",
        manageAllAccess: "모든 액세스 관리",
        manageUsers: "사용자 관리",
        manageLocks: "잠금 관리",
        manageAccess: "액세스 관리",
        mangeMorseCode: "모스 부호 관리",
        viewAuditReport: "감사 보고서보기",
        manageOperationalPermission: "운영 권한 관리",
        viewGroupsInfo: "그룹 정보보기",
        viewAllLocksInAssignedGroups: "할당 된 그룹의 모든 잠금보기",
        viewAllAccessHistory: "할당 된 그룹의 모든 액세스 기록보기",
        receiveBluetooth: "블루투스 / 연결 알림 수신",
        initiateFirmwareUpdates: "펌웨어 업데이트 시작",
        viewAdvanceAuditReport: "고급 감사 보고서보기",
        viewAllGroupsInfo: "모든 그룹 정보보기",
        manageGroups: "그룹 관리",
        manageAdmins: "관리자 관리"
    },
    route: {
        advanceAuditReport: "고급 감사 보고서"
    },
    errorCodes: {
        code_9999: "관리자가 귀하의 계정을 삭제했습니다",
        code_500000: "오류",
        code_400000: "데이터가 변경되었습니다. 페이지를 새로 고침하십시오.",
        code_400001: "이메일 주소는 이미 사용 중입니다",
        code_400002: "잘못된 인증 코드",
        code_400003: "사용자가 승인되었습니다",
        code_400004: "올바른 초대 코드를 입력하십시오",
        code_400005: "사용자가 처리되지 않았거나 떠나거나 동결되도록 설정되었습니다",
        code_400006: "이메일이나 비밀번호가 틀 렸습니다",
        code_400007: "계정 상태에 오류가 있습니다.",
        code_400008: "엔터프라이즈 관리 앱에 로그인 할 권한이 없습니다",
        code_400009: "회사에서 모든 사용자를 제거 할 때까지 삭제할 수 없습니다",
        code_400010: "이메일이 존재하지 않습니다",
        code_400011: "이미 존재하는 그룹 이름",
        code_400012: "모든 사용자가이 그룹에서 재 할당 될 때까지이 그룹을 삭제할 수 없습니다",
        code_400013: "데이터가 변경되었습니다.",
        code_400014: "MAC가 이미 존재합니다",
        code_400015: "이 Tapplock Box는 회사에서 사용 중이므로 삭제할 수 없습니다",
        code_400016: "이 지문은 이미 기록되었습니다",
        code_400017: "이 계정에는 모스 부호를 관리 할 수있는 올바른 권한이 없습니다",
        code_400018: "이전 비밀번호가 잘못되었습니다",
        code_400019: "먼저이 그룹의 잠금 및 사용자를 재 지정하거나 제거하십시오.",
        code_400020: "이 Tapplock Box가 등록되지 않았거나 다른 회사에 등록되었습니다",
        code_400021: "잠금 이름이 이미 존재합니다",
        code_400022: "승인이 취소되었습니다",
        code_400023: "잘못된 초대 코드",
        code_400024: "그룹을 삭제하기 전에이 그룹의 기존 초대 코드를 모두 삭제하십시오",
        code_400026: "마스터 계정은 삭제할 수 없습니다.",
        code_400027: "하나 이상의 그룹이 있어야합니다",
        code_400028: "사용자에게 잠금 권한이 없거나 권한이 취소되었습니다.",
        code_400029: "그룹 아래에 잠금이있어 그룹을 삭제할 수 없습니다",
        code_400030: "관리자가 승인하기를 기다리는 중",
        code_400031: "무료 라이센스 요금으로 인해 회사 계정이 정지되었습니다.",
        code_400032: "결제 실패.",
        code_400033: "결제 메시지 초기화 실패",
        code_400034: "주문이 진행 중입니다.",
        code_400035: "추가 된 총 잠금 수가 한계에 도달했습니다.",
        code_400037: "처음 로그인하는 경우 비밀번호를 변경하십시오.",
        code_400038: "라벨이 이미 존재합니다.",
        code_400040: "다른 그룹의 사용자를 삭제할 수 없습니다",
        code_400041: "자신을 삭제할 수 없습니다",
        code_400042: "잘못된 인증 코드",
        code_400043: "잘못된 CVC",
        code_400044: "카드 거절",
        code_400045: "만료 된 카드",
        code_400046: "카드를 처리하는 중에 오류가 발생했습니다.",
        code_400047: "지불 청구서 없음",
        code_400048: "카드 유효 기간이 유효하지 않습니다."
    },
    advanceAuditReport: {
        openLockBluetooth: null,
        openLockFingerprint: "# {userName} (# {mail})이 지문을 통해 자물쇠 # {targetLockName}을 (를) 열었습니다.",
        syncLocation: "# {userName} (# {mail}) 동기화 된 # {targetLockName} 위치 주소 : # {location}",
        syncBattery: "# {userName} (# {mail}) 동기화 된 # {targetLockName} 배터리",
        close: "# {targetLockName}이 잠겼습니다.",
        morseOpen: "# {targetLockName}이 (가) Morse 코드로 열렸습니다",
        unknownAddress: "알 수없는 주소",
        enrolledFingerprint2: "# {userName} (# {mail})은 # {targetUserName} (# {targetUserMail})의 # {handType} # {fingerType}의 지문을 등록했습니다.",
        noPermission: "none",
        noGroup: "none",
        authNameBluetooth: "블루투스",
        authNameFingerprint: "지문",
        addAuthBluetoothBatch: "# {userName} (# {mail}) 인증 # {targetUserName} (# {targetUserMail}) 일괄 인증을 통해 # {targetLockName}에 대한 영구적 인 블루투스 액세스",
        addAuthFingerprintBatch: "# {userName} (# {mail}) 인증 # {targetUserName} (# {targetUserMail}) 일괄 인증을 통해 # {targetLockName}에 대한 영구 지문 액세스",
        addLockAndAuth: "# {userName} (# {mail})이 추가 된 후 # {targetLockName} 및 인증 된 # {authName}",
        handType_0: "왼손",
        handType_1: "오른손",
        fingerType_0: "무지",
        fingerType_1: "색인",
        fingerType_2: "중간",
        fingerType_3: "반지",
        fingerType_4: "작은"
    },
    auditReport: {
        authFingerprint: "# {operatorName} (# {operatorMail}) 인증 된 # {userName} (# {mail}) # {lockName}에 대한 영구 지문 액세스",
        authBluetooth: "# {operatorName} (# {operatorMail}) 인증 # {userName} (# {mail}) # {lockName}에 대한 영구적 인 블루투스 액세스",
        cancelFingerprint: "# {operatorName} (# {operatorMail})이 # {userName} (# {mail}) # {lockName}에 대한 영구 지문 액세스를 취소했습니다.",
        cancelBluetooth: "# {operatorName} (# {operatorMail})이 # {userName} (# {mail})에서 # {lockName}에 대한 영구적 인 블루투스 액세스를 취소했습니다.",
        authTemp: "# {operatorName} (# {operatorMail}) 인증 된 # {userName} (# {mail}) 임시 블루투스 액세스 (# {times}) ~ # {lockName}",
        cancelTemp: "# {operatorName} (# {operatorMail})이 (가) # {userName} (# {mail}) 임시 블루투스 액세스 (# {time})를 # {lockName} (으)로 취소했습니다.",
        cancelAllTemp: "# {operatorName} (# {operatorMail})이 # {lockName}에 대한 모든 임시 블루투스 액세스를 취소했습니다. # {userName} (# {mail})",
        syncFirmware: "# {operatorName} (# {operatorMail}) 업데이트 된 {{lockName} 펌웨어"
    }
}