export default {
    "format_new_ota_firm_version": "새로운 OTA 펌웨어 버전 : %1$s | %2$s",
    "prompt_ota_firmware_update": "OTA 펌웨어 업데이트",
    "net_code_400051": "선택한 하나 이상의 잠금이 이미 오프라인 모드에 있습니다. 다시 시도하십시오.",
    "hint_offline_user_exit_no_lock_connect": "동기화가 완료 될 때까지 오프라인 모드를 종료 할 수 없습니다.",
    "hint_offline_data_not_synced": "다시 시도하십시오. 오프라인 모드 상태는 인터넷에 연결된 Tapplock 서버와 동기화되어야합니다.",
    "prompt_add_finger": "손가락 추가",
    "hint_lock_user_name": "자물쇠 이름/사용자 이름",
    "format_new_firm_version": "새로운 펌웨어 버전: %s | %s",
    "prompt_morse_set_length": "이제 Tapplock에서 모스코드를 6-12자 길이로 설정하십시오.",
    "hint_morse_all_same": "모스코드는 모두 같은 조합일 수 없습니다. 암호에는 길고 짧은 누름이 있어야 합니다.",
    "hint_insert_box": "Tapplock box (지문등록기)를 연결하십시오.",
    "hint_add_lock_operation": "전원버튼 두 번 (2) 누르면 파란색 LED가 깜빡입니다",
    "format_low_power": "%s의 배터리잔량이 20 %%보다 낮으면 충전하십시오",
    "format_new_firm": "새로운 업그레이드 패키지 %s을 (를) 업데이트 할 준비가 되었습니다. 자물쇠를 업데이트 하십시오.",
    "format_firm_sync": "%s가 업데이트 되어있지 않습니다. 정상적인 사용을 위해 신속히 펌웨어 업데이트 하십시오",
    "format_his_auth_auth_ble": "%1$s %2$s 님이 %3$s %4$s 에게 %5$s 자물쇠에 대한 영구적인 블루투스 권한을 승인하였습니다",
    "format_his_auth_cancel_ble": "%1$s %2$s 님이 %3$s %4$s 에게 %5$s 자물쇠에 대한 영구적인 블루투스 권한을 해지하였습니다",
    "format_hit_auth_auth_temp": "%1$s %2$s 님이 %3$s %4$s 에게 %5$s 에서 %6$s 까지 일시적인 블루투스 액세스를 승인하였습니다",
    "format_hit_auth_revoke_temp": "%1$s %2$s 님이 %3$s %4$s 에게 %5$s 에서 %6$s 까지 일시적인 블루투스 액세스를 해지하였습니다",
    "format_hit_auth_revoke_all_temp": "%1$s %2$s 님이 %3$s %4$s 에게 %5$s 에 대한 모든 임시 블루투스 접속이 취소되었습니다",
    "format_his_set_morse": "%1$s 님이 Morse 코드를 %2$s (으)로 삭제했습니다.",
    "format_his_delete_morse": "%1$s 이 (가) %2$s 에 모스 부호를 작성했습니다",
    "prompt_setup_morse_code": "모스코드 설정",
    "prompt_lock_sync_start": "데이터 동기화중, 블루투스를 끄지 마십시오.",
    "prompt_success_auth_user": "지문액세스에 대한 변경사항은 스태프앱(staff app)에 의해 한 번 동기화 됩니다",
    "prompt_add_lock": "Tapplock 추가…",
    "prompt_not_show_again": "다시 표시하지 않음",
    "hint_lock_ble_unauth": "권한승인되지 않은 블루투스 액세스",
    "hint_lock_ble_auth": "권한승인된 블루투스 액세스",
    "prompt_delete_morse_success": "모스코드 변경은 스태프앱 (Staff app)에서 한번 데이터 동기화 되어야 사용 할 수 있습니다",
    "hint_lock_finger_wait_add": "지문액세스는 스태프앱 (Staff app)에서 한번 데이터 동기화 되어야 사용 할 수 있습니다",
    "hint_lock_finger_wait_delete": "지문액세스는 스태프앱 (Staff app)에서 한번 동기화 되어야 삭제 할 수 있습니다",
    "prompt_report_auth_ble": "권한승인된 블루투스액세스",
    "prompt_report_revoke_ble": "해지된 블루투스액세스",
    "prompt_report_create_morse": "모스코드 생성",
    "prompt_report_delete_morse": "모스 부호 삭제",
    "format_action_count": "감사보고서: %1$d 개 항목",
    "hint_temp_access_auth": "권한승인된 일시적인 블루투스 액세스",
    "hint_add_temporary_success": "임시적인 액세스 권한추가 성공!",
    "hint_remove_lock_all_temp": "%1$s에서 임시적인 액세스를 모두 제거 하시겠습니까?",
    "hint_remove_lock_one_temp": "%1$s에서 임시적인 액세스 (%2$s)을 제거 하시겠습니까?",
    "hint_remove_user_all_temp": "%1$s 의 모든 임시적인 액세스를 제거 하시겠습니까?",
    "hint_remove_user_one_temp": "%1$s 의 임시적인 액세스 (%2$s)을 제거 하시겠습니까?",
    "title_license_agreement": "Tapplock라이센스 계약",
    "prompt_tutorial_sync": "자물쇠를 열려면 등록 지문 변경 사항을 동기화하는 방법?",
    "prompt_firm_download": "블루투스 설치 펌웨어를 다운로드 중입니다. 잠시 기다리지 마십시오.",
    "prompt_dfu_lock_ble_hint": "잠시 기다리지 말고 Bluetooth를, 종료하십시오.",
    "prompt_dfu_success": "펌웨어 업데이트 완료!",
    "prompt_dfu_fail": "펌웨어 업데이트 실패!",
    "prompt_location_permission_info_less": "위치 권한이 설정되어 있지 않으면 블루투스를 통해 잠금을 앱에 연결할 수 없습니다.",
    "prompt_location_permission_info_more": "Tapplock 앱은 장치에서 위치를 가져 오려면 인터넷 및 위치 권한이 필요합니다. Tapplock 앱은 전화와 위치를 파악할 수있는 인터넷과 위치 권한이 필요하기 때문에 블루투스와 관련된 모든 기능의 경우 위치 권한이 켜져 있어야합니다. 그렇지 않으면 새 잠금을 추가하거나 블루투스를 통해 앱에 잠금을 연결하거나 블루투스를 통해 잠금을 열거 나 잠금을 동기화하거나 잠금을 삭제할 수 없습니다.",
    "format_audit_create_user": "%1$s 에서 계정을 만들었습니다 (이메일: %2$s 이름: %3$s)",
    "format_audit_update_user_group": "%1$s %2$s 그룹을 %3$s에서 %4$s로 변경했습니다",
    "format_audit_update_user_permission": "%1$s는 %2$s의 권한을 %3$s에서 %4$s로 변경했습니다",
    "format_audit_update_user_name": "%1$s %2$s의 이름을 %3$s로 변경",
    "format_audit_delete_user": "%1$s 사용자를 삭제했습니다 (이메일: %2$s 이름: %3$s)",
    "format_audit_staff_login": "%1$s 로그인",
    "format_audit_add_rel_bluetooth": "%1$s 인증 %2$s  %3$s 에 대한 영구적 인 블루투스 액세스",
    "format_audit_delete_rel_bluetooth": "%1$s 님이 %3$s 에서 %2$s 영구적 인 블루투스 액세스를 취소했습니다",
    "format_audit_set_morse_code": "%1$s 이 (가) %2$s 에 모스 부호를 작성했습니다",
    "format_audit_add_rel_temp": "%3$s 에 %1$s 의 인증 된 %2$s 의 임시 블루투스 액세스",
    "format_audit_delete_rel_temp": "%1$s 이 (가) %3$s 에 대한 임시 블루투스 액세스를 %2$s 취소",
    "format_audit_delete_all_rel_temp": "%1$s 이 (가) %3$s 에 대한 모든 임시 블루투스 액세스를 %2$s 취소했습니다.",
    "format_audit_delete_morse": "%1$s 모스 부호를 %2$s (으)로 삭제",
    "hint_staff_id": "직원 ID",
    "format_staffId": "직원 ID: %1$s",
    "format_edit_stripe_card": "**** **** **** %1$s (으)로 무엇을 하시겠습니까?",
    "net_code_400008": "엔터프라이즈 시스템 (enterprise admin system)에 접근 권한이 없습니다",
    "net_code_400009": "회사의 모든 사용자가 제거 될 때까지 삭제할 수 없습니다.",
    "net_code_400012": "그룹의 모든 사용자가 제거 될 때까지 그룹을 삭제할 수 없습니다",
    "net_code_400014": "MAC가 이미 존재합니다.",
    "net_code_400015": "Tapplock Box (지문등록기)가 회사에서 사용중이므로 삭제할 수 없습니다",
    "net_code_400017": "모스코드를 관리할 수 있는 권한이 없습니다",
    "net_code_400021": "자물쇠 이름이 이미 사용중입니다",
    "net_code_400022": "권한승인이 취소되었습니다.",
    "net_code_400023": "초대코드가 만료되었습니다",
    "net_code_400026": "마스터 계정은 삭제할 수 없습니다",
    "net_code_400028": "사용자는 자물쇠에 대한 권한이 승인되어 있지 않거나 승인취소 되었습니다",
    "net_code_400031": "라이센스비용을 지불하지 않아 회사계정이 정지되었습니다. 회사의 마스터등급 계정을 통해 지불 하십시오.",
    "net_code_400035": "추가된 총 자물쇠 수는 허용치를 초과하였습니다. 계정관리자에게 문의하십시오.",
    "net_code_400046": "카드를 처리하는 중에 오류가 발생했습니다.",
    "hint_error_time_out": "시간초과",
    "prompt_admin_view": "모든 그룹정보 보기",
    "prompt_manager_morse": "모스코드 관리",
    "prompt_user_notification": "블루투스/연결 알림 수신",
    "prompt_assigned_users": "할당 된 사용자",
    "prompt_assigned_locks": "할당 된 잠금",
    "prompt_add_a_new_box": "새 상자 추가",
    "prompt_choose_a_box": "상자를 선택하십시오",
    "hint_delete_morse": "이 잠금은 모스 코드로 설정되어 있으며 삭제 버튼을 눌러 모스 코드를 제거하십시오. 모스 코드는 잠금 장치를 연결하면 재설정됩니다.",
    "prompt_unregistered": "미등록",
    "prompt_connect": "잇다",
    "format_remain_finger": "남은 지문 : %1$d",
    "prompt_update": "최신 정보",
    "prompt_reset": "다시 놓기",
    "prompt_edit_box": "편집 상자",
    "hint_box_name_empty": "상자 이름을 입력하십시오",
    "prompt_reset_box": "재설정 상자",
    "format_delete_box": "%1$s 상자를 삭제 하시겠습니까?",
    "hint_finger_enroll_exist": "지문이 이미 존재하며 반복적으로 입력 할 수 없습니다",
    "hint_finger_enroll_timeout": "지문 등록 시간이 초과되었습니다. 다시 시도하십시오",
    "hint_finger_enroll_fail": "지문을 등록하지 못했습니다. 손가락을 지문 센서에 다시 놓으십시오.",
    "prompt_box_name": "상자 이름",
    "prompt_action": "동작",
    "format_audit_add_box": "%1$s Tapplock box %2$s 추가",
    "format_audit_update_box_name": "%1$s 가 Tapplock box %2$s 이름을 %3$s (으)로 수정했습니다.",
    "format_audit_delete_box": "%1$s 삭제 된 Tapplock box %2$s",
    "format_hand_finger": "손 %1$s 손 지문 %2$s ",
    "hint_connect_box": "Tapplock box를 연결하십시오",
    "hint_add_box_success": "박스가 성공적으로 등록되었습니다",
    "hint_no_permission_to_edit_finger": "지문 정보를 볼 권한이 없습니다.",
    "hint_no_permission_to_edit_user_label": "사용자 라벨을 수정할 수있는 권한이 없습니다.",
    "prompt_ignore_this_version": "이 버전을 무시하십시오",
    "hint_box_connect_success": "Tapplock box가 성공적으로 연결되었습니다.",
    "hint_box_connect_fail": "연결에 실패했습니다. 다시 시도하십시오.",
    "hint_delete_finger": "이 지문을 삭제 하시겠습니까?",
    "hint_open_box_power": "전원을 켜려면 파란색 LED가 깜박일 때까지 전원 버튼을 길게 누르십시오.",
    "format_audit_enroll_finger": "등록 지문 %1$s",
    "format_audit_remove_finger": "%1$s 지문 삭제",
    "prompt_report_send_delete_finger": "지문 삭제",
    "prompt_report_send_add_box": "상자 추가",
    "prompt_report_send_update_box_name": "업데이트 상자 이름",
    "prompt_report_send_delete_box": "상자 삭제",
    "prompt_report_send_action_unlock_bluetooth": "블루투스 잠금 해제",
    "prompt_report_send_action_unlock_fingerprint": "지문 잠금 해제",
    "prompt_report_send_action_unlock_morse_code": "모스 코드 잠금 해제",
    "prompt_report_send_action_close_lock": "잠금 장치 닫기",
    "prompt_report_send_action_update_location": "위치 업데이트",
    "prompt_report_send_action_update_battery": "배터리 업데이트",
    "action_add": "더하다",
    "action_login": "로그인",
    "action_register_code": "인증코드 전송",
    "action_resend": "재전송",
    "action_save": "저장",
    "action_yes": "예",
    "action_no": "아니오",
    "action_home": "홈",
    "action_user": "사용자",
    "action_lock": "자물쇠",
    "action_setting": "설정",
    "action_authorize_access": "액세스 권한승인",
    "action_add_fingerprint": "지문추가",
    "prompt_forgot_password": "비밀번호를 잊으셨나요",
    "prompt_group": "그룹",
    "prompt_add_group": "그룹추가",
    "prompt_edit_group": "그룹편집",
    "format_delete_group": "%1$s 라는 그룹을 삭제하시겠습니까?",
    "prompt_delete_group": "그룹삭제",
    "prompt_profile": "프로필",
    "prompt_name": "이름",
    "prompt_phone_number": "전화번호",
    "prompt_phone": "전화",
    "prompt_email": "이메일",
    "prompt_fingerprint": "지문",
    "prompt_manager": "매니저",
    "prompt_personal_info": "개인정보",
    "prompt_contact_info": "연락처정보",
    "prompt_first_name": "이름",
    "prompt_last_name": "성",
    "prompt_register_time": "등록시간",
    "prompt_last_login_time": "마지막으로 로그인된 시간",
    "prompt_finger": "지문",
    "prompt_status": "상태",
    "hint_mail": "메일",
    "hint_password": "비밀번호",
    "format_resend_countdown": "%1$ds 후 다시 보내기",
    "hint_firstName": "이름",
    "hint_lastName": "성",
    "hint_phone": "전화",
    "hint_group_name": "그룹이름",
    "hint_name_phone_email": "사용자이름/전화번호/이메일",
    "prompt_save_success": "저장성공",
    "hint_success_add_group": "그룹 추가됨",
    "hint_success_delete_group": "그룹 삭제됨",
    "label_tapplock": "Tapplock",
    "label_ads": "스마트 지문인식 자물쇠",
    "label_sign_in": "로그인",
    "prompt_permission": "허가",
    "prompt_hand": "손",
    "prompt_fingerprint_entry": "지문입력",
    "prompt_enrol_finger": "지문등록기에 지문을 대십시오",
    "prompt_fingers_title": "지문정보",
    "prompt_box": "Box (지문등록기)",
    "prompt_box_serial_no": "Box (지문등록기) 일련번호",
    "prompt_lock_type": "자물쇠 유형",
    "prompt_last_sync_time": "마지막으로 동기화된 시간",
    "prompt_firmware_version": "펌웨어버전",
    "prompt_battery": "배터리",
    "prompt_bluetooth": "블루투스",
    "action_done": "완료",
    "action_cancel": "취소",
    "prompt_map": "지도",
    "prompt_lock_name": "자물쇠 이름",
    "prompt_edit_user": "사용자 편집",
    "prompt_admin": "관리자",
    "prompt_user": "사용자",
    "hint_lock_name": "자물쇠 이름",
    "hint_user_name": "사용자 이름",
    "prompt_wait_delete": "삭제됨",
    "prompt_pending": "보류",
    "prompt_lock_actions": "자물쇠 작동",
    "prompt_add_a_new_tapplock": "새 Tapplock 추가",
    "hint_tapplock_name": "Tapplock 이름",
    "prompt_connected": "연결됨",
    "action_firmware_update": "펌웨어 업데이트",
    "prompt_firmware_update": "펌웨어 업데이트",
    "action_mose_code": "모스코드",
    "action_all": "전체",
    "action_authorized": "권한승인됨",
    "action_unauthorized": "권한승인없음",
    "prompt_update_content": "컨텐츠 업데이트",
    "action_update_now": "지금 업데이트",
    "prompt_morse_code": "모스코드",
    "prompt_morse_code_setup_info": "모스코드는 지문이나 휴대전화가 없는 비상상황 시 길거나 짧게 전원버튼을 사용하여 자물쇠를 열 수 있는 백업액세스 모드입니다. \\n\\n 설정 후, 전원버튼을 세 번 (3) 눌러 모스코드 모드에 진입하여 설정된 조합으로 잠금을 열 수 있습니다",
    "prompt_morse_code_short_info": "모스코드 입력에는 길고(long) 짧은(short) 두 가지 유형이 있습니다. \\n\\n 전원버튼을 짧게 누르면 파란색 LED가 깜박이며 짧은(short) 코드가 입력됩니다.",
    "prompt_morse_code_long_info": "전원버튼을 2초동안 길게 누르고 있으면 긴(long) 코드가 입력되고 LED가 흰색으로 깜박입니다.",
    "prompt_short_code": "짧은(short) 코드",
    "prompt_long_code": "긴(long) 코드",
    "action_short": "짧게(short)",
    "action_long": "길게(long)",
    "action_delete": "삭제",
    "prompt_delete_lock": "자물쇠 삭제",
    "prompt_tel": "전화번호",
    "prompt_post_code": "우편번호",
    "prompt_address": "주소",
    "prompt_company_information": "회사정보",
    "prompt_personal_information": "개인정보",
    "prompt_group_all": "전체그룹",
    "prompt_picture": "사진",
    "action_reset": "리셋",
    "action_user_profile": "사용자편집",
    "action_tutorial": "튜토리얼",
    "action_box_management": "Box(지문등록기) 관리",
    "action_update_pass": "비밀번호변경",
    "action_about": "회사소개",
    "prompt_register_user": "등록 된 사용자",
    "prompt_register_lock": "등록 된 자물쇠",
    "prompt_groups": "그룹",
    "prompt_choose_a_lock": "Tapplock을 선택",
    "action_edit_access": "액세스편집",
    "hint_select_hand": "오른손/왼손 선택하십시오",
    "hint_select_finger": "손가락을 선택하십시오",
    "prompt_group_proportion": "그룹 비율",
    "prompt_access_proportion": "액세스 비율",
    "prompt_group_unlock_activity": "그룹 잠금해제 활동",
    "prompt_group_information": "그룹 정보",
    "format_total_pie": "총 \\n %1$s",
    "prompt_legend_access_finger": "지문 액세스",
    "prompt_legend_access_ble": "블루투스 액세스",
    "prompt_unlock": "잠금해제",
    "prompt_most_active_users": "가장 활동적인 사용자",
    "prompt_most_active_locks": "가장 활동적인 자물쇠",
    "prompt_fingerprint_access": "지문 액세스",
    "prompt_bluetooth_access": "블루투스 액세스",
    "prompt_audit_report": "감사보고서",
    "prompt_time": "시간",
    "prompt_lock_activity": "자물쇠 활동내역",
    "prompt_last_sync_location": "마지막으로 동기화된 위치",
    "action_menu_edit": "편집",
    "action_menu_delete": "삭제",
    "prompt_edit_user_info": "사용자정보 편집",
    "prompt_access": "액세스",
    "prompt_authorization": "권한승인",
    "prompt_user_activity": "사용자 활동",
    "format_data_sync": "%s의 데이터가 업로드되지 않았습니다.",
    "format_his_access_open": "%1$s %2$s 님이 %3$s 자물쇠를 열었습니다",
    "format_his_auth_auth_finger": "%1$s %2$s 님이 %3$s %4$s 에게 %5$s 자물쇠에 대한 영구적인 지문액세스 권한을 승인하였습니다",
    "format_his_auth_cancel_finger": "%1$s %2$s 님이 %3$s %4$s 에게 %5$s 자물쇠에 대한 영구적인 지문액세스 권한을 해지하였습니다",
    "format_his_sync_location": "%1$s %2$s 님이 %3$s 자물쇠 위치 동기화 하였습니다",
    "format_his_sync_firm": "%1$s %2$s 님이 %3$s 자물쇠 펌웨어 업데이트 하였습니다",
    "format_his_sync_battery": "%1$s %2$s 님이 %3$s 배터리 동기화 하였습니다",
    "prompt_pass_length_short": "비밀번호는 8자 이상이어야 합니다",
    "prompt_fill_in_pass": "비밀번호를 입력하십시오",
    "prompt_fill_in_confirm_pass": "비밀번호를 확인하십시오",
    "prompt_fill_in_first_name": "이름을 입력하십시오",
    "prompt_fill_in_last_name": "성을 입력하십시오",
    "prompt_fill_in_old_pass": "기존 비밀번호를 입력하십시오",
    "prompt_pass_mismatch_repass": "비밀번호가 일치하지 않습니다",
    "prompt_pass_same_to_old": "기존 비밀번호는 사용할 수 없습니다",
    "prompt_verification_code": "인증코드",
    "prompt_new_password": "새로운 비밀번호",
    "prompt_update_password_success": "비밀번호가 변경되었습니다",
    "prompt_change_password_success": "비밀번호가 변경되었습니다",
    "hint_end_time_after_begin_time": "종료 시간은 시작 시간보다 늦어야 합니다",
    "hint_start_time_after_now": "시작 시간은 지금보다 늦어야합니다.",
    "prompt_start_time": "시작시간",
    "prompt_end_time": "종료시간",
    "hint_group_name_empty": "그룹명을 입력하십시오",
    "action_logout": "로그아웃",
    "prompt_logout_message": "로그아웃 하시겠습니까?",
    "prompt_to": "To",
    "format_version": "버전: %1$s",
    "prompt_invalid_lock_name": "자물쇠 이름 오류",
    "hint_input_lock_name": "자물쇠 이름을 입력하십시오",
    "hint_select_group": "그룹을 선택하십시오",
    "prompt_error_format_email": "유효하지 않은 이메일 형식",
    "prompt_fill_in_email": "이메일을 작성하십시오",
    "prompt_fill_in_email_code": "인증코드를 입력하십시오",
    "prompt_delete_lock_success": "Tapplock이 삭제되었습니다. 재설정하려면 Tapplock 앱에 다시 연결하십시오",
    "notification_channel_name": "자물쇠 데이터 동기화",
    "notification_channel_dfu_name": "자물쇠 업그레이드",
    "notification_channel_fire_name": "메시지",
    "prompt_edit_lock_name": "자물쇠 이름 편집",
    "prompt_lock_first_fail": "이 자물쇠는 이미 등록되었습니다",
    "prompt_select_lock": "자물쇠를 선택하십시오",
    "hint_add_finger_success": "손가락추가 성공",
    "prompt_user_change": "계정권한 또는 그룹이 수정되었습니다. 다시 로그인 하십시오",
    "prompt_delete_user": "이 사용자를 삭제 하시겠습니까?",
    "prompt_finger_exist_in_box": "지문이 이미 존재합니다. 정말로 사용하시겠습니까?",
    "prompt_re_enrol": "다시 시도",
    "prompt_yes_user_it": "예. 사용하겠습니다",
    "prompt_lock_sync_finish": "동기화 완료!",
    "prompt_lock_sync_fail": "동기화에 실패했습니다. 다시 시도하십시오.",
    "prompt_success_change_user": "사용자 정보가 업데이트 되었습니다",
    "hint_success_add_lock": "Tapplock 등록 성공",
    "hint_success_update_lock_name": "Tapplock 이름이 저장됨",
    "hint_success_save_morse": "모스코드 저장됨",
    "hint_latest_lock_firm": "이 Tapplock 은 최신 펌웨어로 업그레이드 되었습니다",
    "format_his_close": "%s이 (가) 잠겼습니다",
    "format_his_morse_open": "%s이 (가) 모스코드로 열렸습니다",
    "hint_lock_finger_no": "지문없음",
    "prompt_unauth": "무단",
    "prompt_auth": "인정 받은",
    "prompt_old_pass": "기존 비밀번호",
    "prompt_new_pass": "새로운 비밀번호",
    "prompt_confirm_new_pass": "새로운 비밀번호 확인",
    "prompt_permission_not_enough": "사용자의 권한을 수정할 수 있는 권한이 없습니다",
    "prompt_permission_edit_success": "권한을 성공적으로 수정했습니다",
    "prompt_permission_intro_admin": "관리자등급 권한 (Administrative level). 조직등급 (Organizational) 에서 변경 할 수 있습니다",
    "prompt_permission_intro_admin_users": "매니저 및 사용자 계정상태에 따라 모든 사용자를 보고 편집 할 수 있습니다",
    "prompt_permission_intro_admin_locks": "모든 자물쇠를 추가, 편집 및 삭제 할 수 있습니다",
    "prompt_permission_intro_admin_access": "모든 자물쇠에 대한 사용자 액세스를 추가하거나 삭제 할 수 있습니다",
    "prompt_permission_intro_admin_admin": "마스터계정만 다른 사용자에게 이 권한을 부여 할 수 있습니다. 관리자 계정상태에 따라 다른 사용자를 관리하고 모든 그룹 정보를 볼 수 있으며 모든 사용자와 자물쇠를 볼 수 있습니다.",
    "prompt_permission_intro_admin_groups": "그룹을 추가, 편집 및 삭제합니다",
    "prompt_permission_intro_admin_view": "모든 사용자와 자물쇠를 볼 수 있습니다",
    "prompt_permission_intro_admin_report": "시스템에서 모든 사용자 활동내역을 볼 수 있습니다",
    "prompt_permission_intro_manger": "관리등급 (Management level) 사용권한. 사용자가 속한 그룹 내에서 변경 작업을 수행 할 수 있습니다.",
    "prompt_permission_intro_manger_users": "사용자 계정상태에 따라 지정된 그룹내의 사용자를 보고 편집 할 수 있습니다",
    "prompt_permission_intro_manger_locks": "지정된 그룹내에서 자물쇠를 추가, 편집 또는 삭제할 수 있습니다",
    "prompt_permission_intro_manger_access": "지정된 그룹내에서 자물쇠에 대한 사용자 액세스를 추가하거나 삭제할 수 있습니다",
    "prompt_permission_intro_manger_morse": "지정된 그룹내에서 모스코드를 지정, 편집 또는 삭제할 수 있습니다",
    "prompt_permission_intro_manger_manger": "마스터계정 (Master) 또는 관리자계정 (Admin) 상태에 따라 다른 사용자에게 이 권한을 부여 할 수 있습니다. 관리자 계정상태에 따라 다른 사용자를 관리 할 수 있습니다.",
    "prompt_permission_intro_manger_view": "지정된 그룹내의 모든 사용자 및 자물쇠를 볼 수 있습니다.",
    "prompt_permission_intro_users": "사용자등급 (User level) 사용권한. 직원 앱과 관련된 기본 수준의 권한을 가질 수 있습니다.",
    "prompt_permission_intro_users_locks": "사용자가 속한 모든 그룹의 자물쇠를 볼 수 있습니다",
    "prompt_permission_intro_users_history": "사용자에게 지정 된 자물쇠의 액세스 사용내역을 볼 수 있습니다",
    "prompt_permission_intro_users_notification": "블루투스 연결 및 잠금해제에 대한 실시간 알림 수신 가능",
    "prompt_permission_intro_users_firm": "블루투스를 연결하여 자물쇠 펌웨어를 업그레이드 할 수 있습니다.",
    "hin_uncheck_manager_permission": "먼저 사용자의 매니저권한 (manager permission)을 제거한 다음 관리자권한 (admin permission) 을 선택하십시오.",
    "prompt_registered": "등록됨",
    "prompt_not_registered": "등록되지 않은",
    "prompt_last_week": "지난 주",
    "prompt_last_moth": "지난 달",
    "prompt_lock_status": "자물쇠 상태",
    "hint_add_stripe_card_fail": "카드를 추가할 수 없습니다",
    "prompt_add_card": "카드 추가",
    "hint_stripe_update_info_fail": "업데이트 실패",
    "prompt_not_payed": "미납",
    "prompt_bills": "청구서",
    "prompt_invoice_number": "청구서 No.",
    "prompt_bill_title": "결제주기",
    "prompt_unit_price": "$/대당",
    "prompt_number_of_locks": "자물쇠 수",
    "prompt_bill_title_tex": "부가세 ($)",
    "prompt_bill_title_total": "총합 ($)",
    "prompt_bill_title_status": "상태",
    "prompt_paid": "지불완료",
    "prompt_not_pay": "미납",
    "format_bill_to": "%s 청구서",
    "prompt_card": "카드",
    "prompt_pay_now": "결제하기",
    "prompt_bind_card_title": "카드추가",
    "prompt_bind_card_content2": "라이센스 사용료 결제카드를 추가해 주십시오",
    "hint_bind_card_content": "카드가 추가되지 않았습니다. 서비스 사용에 영향을 주지 않으려면 신속히 카드를 추가해 주십시오",
    "prompt_pay_success": "귀하의 회사가 활성화 되었습니다",
    "hint_delete_pay_card_fail": "카드를 삭제하지 못했습니다. 다시 시도하십시오.",
    "prompt_delete_pay_card_title": "카드삭제",
    "prompt_delete_pay_card_content": "정말로 카드를 삭제하시겠습니까?",
    "prompt_finger_check_fail": "지문인식실패. 다시 시도하십시오",
    "prompt_language": "언어",
    "action_report": "보고서",
    "format_please_set": "%1$s을 (를) 설정하십시오",
    "prompt_all_funds": "모두 발견됨",
    "action_delete_lock": "자물쇠 삭제",
    "prompt_upload_avatar": "프로필사진 업로드",
    "prompt_upload_avatar_fail": "프로필사진 업로드 실패, 다시 시도하십시오",
    "prompt_upload_avatar_success": "프로필사진 업로드 성공",
    "prompt_splash_slogan": "중요한 것을 빠르고 쉽게 액세스",
    "prompt_permission_intro_manger_report": "감사보고서 보기 및 내보내기",
    "hin_uncheck_admin_permission": "먼저 사용자의 매니저권한 (manager permission)을 제거한 다음 관리자권한 (admin permission)을 선택하십시오.",
    "prompt_activity_report": "활동보고서",
    "format_pay_summary": "소계: $ %s            부가세: $ %s        총합계: $ %s",
    "prompt_create_users": "사용자생성",
    "prompt_next": "다음",
    "prompt_add": "추가",
    "prompt_export": "내보내기",
    "prompt_report_sign_up": "회원가입완료",
    "prompt_report_login_pad": "엔터프라이즈앱 (enterprise app) 로그인",
    "prompt_report_login_staff": "스태프앱 (staff app) 로그인",
    "prompt_report_change_pass": "비밀번호 변경",
    "prompt_report_change_username": "사용자이름 편집",
    "prompt_report_enroll_finger": "지문등록기",
    "prompt_report_invite_user": "사용자 초대",
    "prompt_report_create_invite_code": "초대코드 생성됨",
    "prompt_report_create_user": "사용자 생성",
    "prompt_report_delete_user": "사용자 삭제",
    "prompt_report_add_lock": "자물쇠 추가",
    "prompt_report_edit_lock_name": "자물쇠 이름 편집",
    "prompt_report_delete_lock": "자물쇠 삭제",
    "prompt_report_sync_data": "자물쇠 데이터 동기화",
    "prompt_report_update_firm": "펌웨어 업데이트",
    "prompt_report_auth_finger": "권한승인된 지문액세스",
    "prompt_report_revoke_finger": "해지된 지문액세스",
    "prompt_report_create_group": "그룹생성",
    "prompt_report_delete_group": "그룹삭제",
    "prompt_report_edit_group_name": "그룹명 편집",
    "prompt_report_edit_user_group": "수정된 사용자 그룹",
    "prompt_report_edit_user_permission": "수정된 사용자 권한",
    "prompt_report_download": "다운로드 된 감사보고서",
    "prompt_report_send_feedback": "피드백 전송완료",
    "prompt_advance_audit_report": "전문감사보고서",
    "format_export_message": "감사보고서는 해당 이메일주소로 전송됩니다: %1$s 감사보고서를 이메일에서 확인하십시오.",
    "prompt_export_excel_file": "감사보고서 내보내기",
    "prompt_export_success": "감사보고서 내보내기 성공",
    "hint_action_search": "사용자이름/이메일/자물쇠 이름",
    "prompt_color": "색상",
    "prompt_label": "레이블",
    "prompt_add_label": "레이블 추가",
    "prompt_label_name": "레이블 이름",
    "prompt_colors": "색상",
    "prompt_input_tag_name": "레이블 이름을 입력하십시오",
    "prompt_delete_tag": "레이블 삭제",
    "format_delete_tag": "\\'%1$s\\' 레이블을 삭제 하시겠습니까?",
    "prompt_lock_information": "자물쇠 정보",
    "prompt_all_labels": "모든 레이블",
    "prompt_disconnect": "연결끊어짐",
    "prompt_lock_info": "자물쇠 정보",
    "prompt_last_update_time": "마지막으로 동기화된 시간",
    "prompt_added_labels": "레이블 추가됨",
    "prompt_unadded_labels": "레이블 추가되지 않음",
    "prompt_edit_labels": "레이블 편집",
    "prompt_edit_label": "레이블 편집",
    "prompt_temporary_access": "임시 액세스",
    "prompt_permanent_access": "영구적인 액세스",
    "prompt_none": "없음",
    "hint_finger_sync": "지문인식 액세스가 이미 있습니다",
    "hint_lock_finger_not_auth": "권한승인되지 않은 블루투스 액세스",
    "format_select_lock": "%1$d 개의 자물쇠가 선택됨",
    "format_select_user": "%1$d 명의 사용자가 선택됨",
    "hint_select_start_time": "시작시간을 선택하십시오",
    "hint_select_end_time": "종료시간을 선택하십시오",
    "hint_add_temporary_time": "임시적인 액세스 시간을 추가하십시오",
    "hint_add_temporary_lock": "임시적인 자물쇠 액세스를 추가하십시오",
    "hint_add_temporary_user": "임시적인 사용자 액세스를 추가하십시오",
    "hint_remove_permanent_access": "임시적인 액세스 권한을 부여하면 영구적인 액세스가 제거됩니다.",
    "hint_remove_temporary_access": "영구적인 액세스 권한을 부여하면 임시적인 액세스가 제거됩니다.",
    "prompt_delete_access": "액세스 삭제",
    "prompt_report_authorized_temp_access": "승인 된 임시 액세스",
    "prompt_report_revoked_temp_access": "임시 액세스 권한 취소",
    "prompt_report_revoked_all_temp_access": "모든 임시 액세스 권한 취소",
    "prompt_select_time": "시간 선택",
    "title_create_users": "사용자생성",
    "title_authorize_temporary_access": "임시적인 액세스 권한승인",
    "title_personal_information": "개인정보",
    "title_unPaid_bills": "미납청구서",
    "prompt_logging_in_info": "로그인하면 Tapplock의 <a href=\"tapplock://com.trapplock.enterprise/license.html\">라이센스 계약에</a> 동의하게됩니다.",
    "prompt_unknown_address": "알 수없는 주소",
    "prompt_tutorial_title": "여기에서 튜토리얼을 선택하면 질문하는 특정 단계로 이동합니다. 이 페이지에서 빠져 나갈 것입니다.",
    "prompt_tutorial_lock": "자물쇠를 추가하는 방법?",
    "prompt_tutorial_user": "사용자를 추가하는 방법은 무엇입니까?",
    "prompt_tutorial_finger": "지문을 추가하는 방법?",
    "prompt_tutorial_access": "액세스를 관리하는 방법은 무엇입니까?",
    "prompt_tutorial_dialog_content": "튜토리얼을 시작하려면 다음을 선택하십시오. 설정을 도와주고 관리 플랫폼을 사용하는 방법을 배우는 몇 가지 단계를 안내해드립니다.",
    "prompt_tutorial_dialog_title": "Tapplock에 오신 것을 환영합니다!",
    "action_skip_tutorial": "자습서 건너 뛰기",
    "prompt_dfu_firm_updating": "펌웨어 업데이트중…",
    "prompt_dfu_install_fail": "설치 실패, 다시 시도하십시오.",
    "prompt_location_permission_title": "응용 프로그램 설정에서 위치 권한을 설정하십시오",
    "prompt_learn_more": "더 알아보기",
    "prompt_go_to_setting": "설정으로 이동",
    "format_audit_sign_up": "%1$s 초대 코드 %2$s 에 가입",
    "format_audit_enterprise_login": "%1$s 엔터프라이즈 시스템에 로그인",
    "format_audit_change_password": "%1$s 비밀번호 변경",
    "format_audit_add_group": "%1$s 창조하다 %2$s",
    "format_audit_delete_group": "%1$s 삭제 %2$s",
    "format_audit_edit_group": "%1$s %2$s 이름을 %3$s로 변경",
    "format_audit_add_invite_code": "%1$s 초대 코드 %2$s 을 (를) 생성했습니다.",
    "format_audit_invite_users_code": "%1$s 님이 %2$s 명의 사용자를 초대했습니다",
    "format_audit_add_lock": "%1$s 추가 %2$s ",
    "format_audit_update_lock_name": "%1$s 님이 %2$s 이름을 %3$s (으)로 수정했습니다",
    "format_audit_delete_lock": "%1$s 이 (가) %2$s 을 (를) 삭제했습니다.",
    "format_audit_add_rel_fingerprint": "%1$s 인증 %2$s  %3$s 에 대한 영구 지문 액세스",
    "format_audit_delete_rel_fingerprint": "%1$s 이 (가) %3$s 에서 %2$s 영구 지문 액세스를 취소했습니다.",
    "format_audit_sync_lock_data": "%1$s 동기화 %2$s ",
    "format_audit_update_firmware": "%1$s 업데이트 %2$s 펌웨어",
    "format_audit_send_feedback": "%1$s 님이 피드백을 보냈습니다",
    "format_audit_enrolled_fingerprint": "등록 지문 %1$s ",
    "format_audit_download_advance_audit_report": "%1$s 다운로드 감사 보고서",
    "prompt_user_info": "사용자 정보",
    "prompt_confirm_page": "확인 페이지",
    "prompt_confirmation": "확인",
    "prompt_user_creation_failed": "사용자 생성 실패",
    "prompt_submit": "제출",
    "prompt_reason": "이유",
    "format_users": "%1$d 명의 사용자",
    "prompt_create_user_content": "사용자 생성 성공",
    "prompt_complete_your_information": "정보를 작성하십시오",
    "prompt_set_as_default": "이 카드를 기본 카드로 설정",
    "prompt_delete_card": "이 카드를 삭제",
    "prompt_all_user_info": "모든 사용자 정보",
    "intro_create_user": "여기에서 검토없이 사용자를 만들 수 있습니다.",
    "intro_add_finger": "핑거 프린트 추가 \\n 사용자의 지문을 추가하려면 여기를 클릭하십시오.",
    "intro_user_permanent_access": "여기에서 사용자 임시 액세스 권한을 부여 할 수 있으며 권한이 부여 된 사용자는 제한된 시간 동안 잠금에 액세스 할 수 있습니다.",
    "intro_user_temporary_access": "여기에서 사용자 임시 액세스 권한을 부여 할 수 있으며 권한이 부여 된 사용자는 제한된 시간 동안 잠금에 액세스 할 수 있습니다.",
    "intro_user_history": "여기에서 사용자가보고있는 기록을 확인할 수 있습니다.",
    "intro_lock_add_lock": "새로운 테이프 플립을 추가하십시오 \\n 새로운 Tapplock을 추가하려면 여기를 클릭하십시오.",
    "intro_lock_permanent_access": "여기에서 사용자 영구 액세스 권한을 부여 할 수 있으며 승인 된 사용자는 언제든지 잠금에 액세스 할 수 있습니다.",
    "intro_lock_temporary_access": "여기에서 사용자 임시 액세스 권한을 부여 할 수 있으며 권한이 부여 된 사용자는 제한된 시간 동안 잠금에 액세스 할 수 있습니다.",
    "intro_lock_history": "여기에서보고있는 Tapplock을 기반으로 기록을 확인할 수 있습니다.",
    "prompt_left": "왼손",
    "prompt_right": "오른손",
    "prompt_finger_thumb": "엄지",
    "prompt_finger_index": "검지",
    "prompt_finger_middle": "중지",
    "prompt_finger_ring": "약지",
    "prompt_finger_little": "소지",
    "net_code_400000": "데이터가 존재하지 않거나 삭제되었습니다",
    "net_code_400001": "이메일이 이미 사용중입니다",
    "net_code_400002": "인증코드가 유효하지 않습니다",
    "net_code_400003": "사용자가 승인되었습니다",
    "net_code_400004": "유효하지 않은 초대코드",
    "net_code_400005": "사용자가 처리되지 않았거나 권한승인거절 또는 권한승인보류로 설정되었습니다",
    "net_code_400006": "올바르지 않은 이메일 또는 비밀번호",
    "net_code_400007": "비정상적 상태입니다",
    "net_code_400010": "이메일이 존재하지 않습니다",
    "net_code_400011": "그룹이 이미 존재합니다",
    "net_code_400013": "데이터가 변경되었습니다. 다시 시도하십시오",
    "net_code_400016": "지문이 이미 존재합니다",
    "net_code_400018": "기존 비밀번호가 올바르지 않습니다",
    "net_code_400019": "그룹을 삭제하기 전에 모든 자물쇠를 삭제하십시오",
    "net_code_400020": "Tapplock Box (지문등록기)가 회사에 연동이 되어 있지 않습니다",
    "net_code_400024": "그룹을 삭제하기 전에 초대코드 사용을 비활성화 하십시오",
    "net_code_400027": "마지막 그룹은 삭제할 수 없습니다",
    "net_code_400029": "그룹의 모든 Tapplock을 먼저 제거하십시오",
    "net_code_400030": "관리자 (admin) 승인 대기중",
    "net_code_400032": "결제실패. 유효한 카드로 결제하거나 다시 시도하십시오",
    "net_code_400033": "결제메시지 초기화 실패",
    "net_code_400034": "주문진행중. 나중에 다시 시도하십시오",
    "net_code_400037": "처음으로 로그인하는 경우 비밀번호를 변경하십시오",
    "net_code_400038": "레이블이 이미 존재합니다",
    "net_code_400043": "잘못된 CVC",
    "net_code_400044": "카드 거절",
    "net_code_400045": "만료 된 카드",
    "net_code_400047": "지불 청구서 없음",
    "net_code_400048": "카드 유효 기간이 유효하지 않습니다",
    "net_not_available": "네트워크를 사용할 수 없음",
    "net_code_unknown": "서버에러",
    "hint_error_network_not_available": "인터넷 연결을 확인하십시오",
    "prompt_admin_user": "모든 사용자 관리",
    "prompt_admin_lock": "모든 자물쇠 관리",
    "prompt_admin_access": "모든 액세스 관리",
    "prompt_admin_manage": "관리자(admin) 관리",
    "prompt_admin_group": "그룹 관리",
    "prompt_admin_report": "모든 전문감사보고서 보기",
    "prompt_manager_user": "사용자 관리",
    "prompt_manager_lock": "자물쇠 관리",
    "prompt_manager_access": "액세스 관리",
    "prompt_manager_history": "감사보고서 보기",
    "prompt_manager_manage": "운영허가 관리",
    "prompt_manager_group": "그룹정보 보기",
    "prompt_user_locks": "지정된 그룹의 모든 자물쇠 보기",
    "prompt_user_history": "지정된 그룹의 액세스 사용내역 보기",
    "prompt_user_firm": "펌웨어 업데이트 시작",
    "prompt_tlbox_disconnect": "Tapplock Box (지문등록기)가 끊어짐",
    "prompt_update_available": "새로운 버전의 앱이 감지되었습니다. 업데이트 하시겠습니까?",
    "prompt_update_force": "새로운 버전의 앱이 감지되었습니다. 계속하려면 업데이트 하십시오",
    "prompt_soft_update": "소프트웨어 업데이트",
    "prompt_retry": "다시 시도",
    "prompt_server_upgrade": "서버점검중. 나중에 다시 시도하십시오",
    "prompt_pay_confirm_content": "이 청구서를 결제 하시겠습니까?"
}